// Browser checks against a running preview. Set PLAYWRIGHT_MODULE when using a bundled runtime.
import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || "playwright");
const url = process.env.STUDY_PREVIEW_URL || "http://127.0.0.1:5173/";
const out = path.resolve("reports/application-remediation");
await mkdir(out, { recursive: true });
const browser = await chromium.launch({ headless: true, args: ["--enable-unsafe-swiftshader"] });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
const errors = [];
const checks = [];
page.on("pageerror", error => errors.push(error.message));
page.setDefaultTimeout(20000);
const check = name => { checks.push(name); console.log(`PASS ${name}`); };
const noOverflow = async () => assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), "horizontal overflow");

try {
  await page.goto(url, { waitUntil: "domcontentloaded" });
  await page.getByRole("heading", { name: "Project register", exact: true }).waitFor();
  assert.equal(await page.locator(".project-card").count(), 36);
  await noOverflow();
  await page.screenshot({ path: path.join(out, "register-desktop.png") });
  check("register shows 36 candidates without overflow");

  await page.getByLabel("Economic evidence", { exact: true }).selectOption("available");
  assert.equal(await page.locator(".project-card").count(), 36);
  await page.getByLabel("Economic evidence", { exact: true }).selectOption("missing");
  assert.equal(await page.locator(".project-card").count(), 0);
  await page.getByRole("heading", { name: "No matching projects" }).waitFor();
  await page.getByRole("button", { name: "Clear filters" }).click();
  check("economic coverage filter reports evidence on all 36 candidates");

  await page.getByLabel("Project type", { exact: true }).selectOption("Private enterprise");
  assert.equal(await page.locator(".project-card").count(), 3);
  await page.getByLabel("State", { exact: true }).selectOption("MI");
  assert.equal(await page.locator(".project-card").count(), 1);
  await page.getByRole("link", { name: "Quicken Loans Technology Center, Corktown", exact: true }).click();
  await page.getByRole("heading", { name: "Sources & research history" }).waitFor();
  assert.equal(await page.locator(".missing-badge").count(), 7);
  assert.deepEqual(await page.locator(".readiness-list strong").allTextContents(), ["Evidence gap", "Evidence gap", "Partial source evidence", "Not model-ready"]);
  check("combined filters and enterprise profile preserve partial economic coverage");

  await page.getByRole("link", { name: "Project study", exact: true }).click();
  await page.getByLabel("Search projects").fill("zzzz-no-project");
  await page.getByRole("heading", { name: "No matching projects" }).waitFor();
  await page.getByRole("button", { name: "Clear filters" }).click();
  assert.equal(await page.locator(".project-card").count(), 36);
  await page.getByLabel("Historical evidence", { exact: true }).selectOption("needs_research");
  assert.equal(await page.locator(".project-card").count(), 3);
  await page.getByRole("link", { name: "Google Lenoir", exact: true }).click();
  await page.getByRole("heading", { name: "Sources & research history" }).waitFor();
  assert.match(await page.locator(".project-tags").innerText(), /Campus-linked project/);
  assert.match(await page.locator(".project-timeline").innerText(), /chronology needs reconstruction/);
  check("empty state, reset and undated campus profile");

  await page.goto(`${url}#/project/prj_study_im3_building_00438078069`);
  await page.getByRole("heading", { name: "Sources & research history" }).waitFor();
  await page.getByText("Inventory identity and earlier first-entry research", { exact: true }).click();
  assert.match(await page.locator(".research-details").filter({ hasText: "Inventory identity and earlier first-entry research" }).innerText(), /cannot be the county's first entry/);
  await page.getByRole("link", { name: /Polk County, IA · Explore community history/ }).click();
  await page.getByRole("heading", { name: "Polk County", exact: true }).waitFor();
  await page.getByRole("link", { name: /Meta Altoona/ }).waitFor();
  assert.equal(await page.locator(".profile-grid").getByText("County first-entry treatment").count(), 0);
  check("rejected first-entry candidate remains accessible through existing county route");

  await page.goto(`${url}#/project/prj_study_im3_building_00116005354`);
  await page.getByRole("heading", { name: "Economic evidence", exact: true }).waitFor();
  assert.equal(await page.locator(".history-bar-row").count(), 13);
  assert.equal(await page.locator(".history-bar-row.uncollected").count(), 5);
  assert.equal(await page.locator(".economic-record").count(), 8);
  assert.match(await page.locator(".economic-history").innerText(), /\$1,476,648,949/);
  await page.locator(".economic-record summary").first().click();
  assert.match(await page.locator(".economic-record").first().innerText(), /tax-base stock, not tax receipts/);
  assert.match(await page.locator(".economic-record details a").first().getAttribute("href"), /#page=242$/);
  await page.locator(".economic-accounts").scrollIntoViewIfNeeded();
  await noOverflow();
  await page.screenshot({ path: path.join(out, "economic-history-desktop.png") });
  await page.setViewportSize({ width: 390, height: 844 });
  await noOverflow();
  await page.locator(".economic-history").screenshot({ path: path.join(out, "economic-history-mobile.png") });
  check("tax-base history shows missing years, county scope and page-level sources on desktop/mobile");

  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto(`${url}#/project/prj_study_im3_building_00464097467`);
  await page.getByRole("tab", { name: /Reported activity/ }).waitFor();
  await page.locator(".economic-record-list").getByText("80 FTE", { exact: true }).waitFor();
  assert.equal(await page.locator(".economic-record").count(), 2);
  assert.match(await page.locator(".economic-record-list").innerText(), /80 FTE/);
  assert.doesNotMatch(await page.locator(".economic-record-list").innerText(), /742,071,428/);
  await page.getByRole("tab", { name: /Reported activity/ }).focus();
  await page.keyboard.press("ArrowRight");
  assert.equal(await page.getByRole("tab", { name: /Plans & forecasts/ }).getAttribute("aria-selected"), "true");
  assert.match(await page.locator(".economic-record-list").innerText(), /\$742,071,428/);
  assert.match(await page.locator(".economic-record-list").innerText(), /10-year estimate/);
  assert.equal(await page.locator(".history-bar-row").count(), 0);
  assert.equal(await page.locator(".coverage-badge").getByText("Projections only", { exact: true }).count(), 2);
  await page.locator(".economic-accounts").scrollIntoViewIfNeeded();
  await page.screenshot({ path: path.join(out, "economic-forecasts-desktop.png") });
  await page.setViewportSize({ width: 390, height: 844 });
  await noOverflow();
  await page.locator(".economic-accounts").screenshot({ path: path.join(out, "economic-forecasts-mobile.png") });
  await page.setViewportSize({ width: 1440, height: 1000 });
  check("actual workforce and forecasts stay separate with distinct horizons and keyboard navigation");

  await page.goto(`${url}#/project/prj_study_im3_point_06685432442`);
  await page.getByRole("heading", { name: "Economic evidence", exact: true }).waitFor();
  await page.getByText("79 sourced records · 34 modeled syntheses", { exact: true }).waitFor();
  assert.match(await page.locator(".economic-record-list").innerText(), /111 employees[\s\S]*\$50\.97 \/ hour[\s\S]*\$179,943,184/);
  const switchAudit = page.locator(".economic-record").filter({ hasText: "State-audited capital expenditure" });
  await switchAudit.locator("summary").click();
  assert.match(await switchAudit.innerText(), /Company \/ county context[\s\S]*unallocated to Tahoe Reno 1/);
  assert.match(await switchAudit.locator("a").getAttribute("href"), /RTTL_NRS231\.0685_2023\.pdf#page=64$/);
  assert.match(await page.locator(".project-research-update").filter({ hasText: "Five-year audit adds jobs" }).innerText(), /Clark County #3 row repeats the same findings/);
  await page.setViewportSize({ width: 390, height: 844 });
  await noOverflow();
  await switchAudit.screenshot({ path: path.join(out, "switch-storey-audit-capex-mobile.png") });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.getByRole("tab", { name: /Plans & forecasts/ }).click();
  assert.equal(await page.locator(".economic-record").count(), 7);
  assert.match(await page.locator(".economic-record-list").innerText(), /50 jobs[\s\S]*\$28\.98 \/ hour[\s\S]*\$1,386,677,024[\s\S]*\$75,720,025[\s\S]*\$32,095,728[\s\S]*\$100,000/);
  await page.setViewportSize({ width: 390, height: 844 });
  await noOverflow();
  await page.locator(".economic-accounts").screenshot({ path: path.join(out, "switch-storey-agreement-forecasts-mobile.png") });
  await page.setViewportSize({ width: 1440, height: 1000 });
  check("Switch Storey audit outcomes remain separate from agreement forecasts and building allocation");

  await page.goto(`${url}#/project/prj_study_im3_building_01132541700`);
  await page.getByRole("heading", { name: "Economic evidence", exact: true }).waitFor();
  await page.locator(".economic-record").first().waitFor();
  assert.equal(await page.locator(".economic-record").count(), 1);
  assert.match(await page.locator(".record-value").innerText(), /More than 1,500 workers/);
  assert.match(await page.locator(".economic-record").innerText(), /Historical construction peak reported 2020-08-05/);
  await page.locator(".economic-record summary").click();
  assert.doesNotMatch(await page.locator(".economic-record details").innerText(), /PDF page|undefined/);
  assert.equal(await page.locator(".economic-record details a").getAttribute("href"), "https://datacenters.atmeta.com/2020/08/henrico-county-we-are-online/");
  await page.getByRole("tab", { name: /Plans & forecasts/ }).click();
  assert.equal(await page.locator(".economic-record").count(), 2);
  assert.match(await page.locator(".economic-record-list").innerText(), /More than \$1,000,000,000/);
  assert.match(await page.locator(".economic-record-list").innerText(), /completion date unspecified/);
  await page.setViewportSize({ width: 390, height: 844 });
  await noOverflow();
  await page.locator(".economic-accounts").screenshot({ path: path.join(out, "qualified-plans-mobile.png") });
  check("qualified peaks and completion-dependent plans preserve wording and HTML source links");

  await page.goto(`${url}#/project/prj_study_im3_building_00397914434`);
  await page.getByRole("heading", { name: "Economic evidence", exact: true }).waitFor();
  assert.match(await page.locator(".economic-record-list").innerText(), /2023 source table/);
  assert.match(await page.locator(".record-value").innerText(), /\$10,375,490/);
  assert.equal(await page.locator(".history-bar-row").count(), 0);
  await noOverflow();
  await page.setViewportSize({ width: 1440, height: 1000 });
  check("county source-year value remains distinct from a fiscal-year series");

  await page.goto(`${url}#/project/prj_study_im3_building_00610827836`);
  await page.getByRole("heading", { name: "Economic evidence", exact: true }).waitFor();
  assert.equal(await page.getByRole("tab", { name: /Plans & forecasts/ }).getAttribute("aria-selected"), "true");
  assert.match(await page.locator(".economic-record-list").innerText(), /\$1,300,000,000/);
  await page.getByRole("tab", { name: /Reported activity/ }).click();
  assert.equal(await page.locator(".economic-record").count(), 0);
  assert.match(await page.locator("#economic-records").innerText(), /No reported activity collected/);
  check("a forecast-only project never displays its plan as reported activity");

  await page.goto(`${url}#/project/prj_study_im3_building_00460089167`);
  await page.getByRole("heading", { name: "Sources & research history" }).waitFor();
  await page.locator(".fiscal-history").waitFor();
  assert.equal(await page.locator(".fiscal-history tbody tr").count(), 5);
  assert.equal(await page.locator(".history-bar-row").count(), 5);
  assert.equal(await page.locator(".economic-record").count(), 20);
  assert.equal(await page.locator(".fiscal-history thead th").count(), 4);
  assert.match(await page.locator(".fiscal-history").innerText(), /\$6,573,472/);
  assert.match(await page.locator(".fiscal-history").innerText(), /\$6,082,555/);
  assert.match(await page.locator(".fiscal-history").innerText(), /provisional/);
  assert.match(await page.locator(".fiscal-history tbody tr").first().innerText(), /FY2021[\s\S]*6,573,472[\s\S]*6,082,555[\s\S]*490,917/);
  assert.match(await page.locator(".fiscal-history tbody tr").last().innerText(), /FY2025[\s\S]*3,901,427[\s\S]*3,582,303[\s\S]*319,124/);
  assert.match(await page.locator(".economic-record-list").innerText(), /At least \$750,000,000[\s\S]*At least 275 jobs[\s\S]*At least \$6,400,000[\s\S]*\$148,900/);
  assert.match(await page.locator(".project-research-update").allInnerTexts().then(rows => rows.join(" ")), /operator factsheet broadens[\s\S]*water-line grant[\s\S]*Brownfield reuse/i);
  await page.locator(".fiscal-history").screenshot({ path: path.join(out, "fiscal-comparison-desktop.png") });
  await page.screenshot({ path: path.join(out, "project-desktop.png") });
  await page.setViewportSize({ width: 390, height: 844 });
  await noOverflow();
  await page.locator(".fiscal-history").screenshot({ path: path.join(out, "fiscal-comparison-mobile.png") });
  await page.screenshot({ path: path.join(out, "project-mobile.png") });
  await page.locator(".economic-accounts").screenshot({ path: path.join(out, "meta-forest-city-depth-mobile.png") });
  await page.getByRole("tab", { name: /Plans & forecasts/ }).click();
  assert.equal(await page.locator(".economic-record").count(), 3);
  assert.match(await page.locator(".economic-record-list").innerText(), /10 jobs[\s\S]*About \$450,000,000[\s\S]*More than 250 workers/);
  check("Forest City depth account separates fiscal arithmetic, current operator claims and original forecasts");

  await page.goto(`${url}#/project/prj_study_im3_building_00978934687`);
  await page.getByRole("heading", { name: "Proposed expansion agreement expired" }).waitFor();
  const hammondExpiry = page.locator(".project-research-update").filter({ hasText: "Proposed expansion agreement expired" });
  assert.match(await hammondExpiry.innerText(), /2026-07-01/);
  assert.match(await hammondExpiry.innerText(), /does not establish closure/);
  await page.getByText("113 sourced records · 43 modeled syntheses", { exact: true }).waitFor();
  await page.getByRole("heading", { name: "Full modeled county account", exact: true }).waitFor();
  assert.equal(await page.locator(".economic-record").count(), 103);
  assert.equal(await page.locator(".tax-billing-history tbody tr").count(), 5);
  assert.match(await page.locator(".tax-billing-history tbody tr").nth(3).innerText(), /2024[\s\S]*\$19,987,700[\s\S]*\$641,685\.14[\s\S]*\$641,685\.14/);
  assert.match(await page.locator(".tax-billing-history tbody tr").last().innerText(), /2025[\s\S]*\$20,014,600[\s\S]*\$640,867\.48[\s\S]*Not collected/);
  assert.match(await page.locator(".economic-record-list").innerText(), /Local property-tax credits[\s\S]*\$95,115\.62/);
  assert.match(await page.locator(".economic-record-list").innerText(), /More than \$50,000,000[\s\S]*\$30,328,680[\s\S]*20 MW[\s\S]*8 generators/);
  assert.match(await page.locator(".economic-record-list").innerText(), /\$211,110,564[\s\S]*\$220,812,911[\s\S]*\$240,300,000[\s\S]*\$249,400,000/);
  assert.match(await page.locator(".economic-record-list").innerText(), /15 MW/);
  assert.match(await page.locator(".economic-record-list").innerText(), /\$7,745,144[\s\S]*\$7,263,439[\s\S]*115,652 square feet[\s\S]*89\.3%/);
  assert.equal(await page.locator(".economic-record").filter({ hasText: "State incentive paid or certified to date" }).count(), 14);
  assert.match(await page.locator(".economic-record-list").innerText(), /\$0[\s\S]*\$9,045,773\.82[\s\S]*\$28,369,398\.27[\s\S]*\$186,954,143[\s\S]*Public infrastructure grant[\s\S]*\$8,000/);
  assert.match(await page.locator(".economic-record-list").innerText(), /\$11,763[\s\S]*State incentive downward adjustment[\s\S]*\$5,209/);
  assert.match(await page.locator(".economic-record-list").innerText(), /IEDC 2021 EICR, cumulative project 419942 edge, paid\/certified to date[\s\S]*IEDC 2023 EICR, cumulative project 419942 edge, paid\/certified to date/);
  assert.match(await page.locator(".economic-record-list").innerText(), /IEDC 2021 EICR, cumulative project 419963 irtc, paid\/certified to date[\s\S]*IEDC 2025 EICR, cumulative project 419963 irtc, paid\/certified to date/);
  assert.match(await page.locator(".economic-record-list").innerText(), /IEDC 2023 EICR, cumulative project 419963 data, paid\/certified to date[\s\S]*IEDC 2025 EICR, cumulative project 419963 data, paid\/certified to date/);
  assert.match(await page.locator(".economic-record-list").innerText(), /17 employees[\s\S]*\$8,040,000/);
  assert.match(await page.locator(".economic-record-list").innerText(), /County data-processing and hosting establishments[\s\S]*7 establishments[\s\S]*County data-processing and hosting employment[\s\S]*67 employees/);
  assert.match(await page.locator(".economic-record-list").innerText(), /County industry context[\s\S]*entire six-digit industry, not Digital Crossroad or Hammond alone/);
  assert.match(await page.locator(".economic-history").filter({ hasText: "County data-processing and hosting employment over time" }).innerText(), /2016[\s\S]*67 employees[\s\S]*2021[\s\S]*429 employees[\s\S]*2023[\s\S]*44 employees/);
  assert.match(await page.locator(".economic-history").filter({ hasText: "County data-processing and hosting annual payroll over time" }).innerText(), /CY2016[\s\S]*\$7,295,000[\s\S]*CY2023[\s\S]*\$4,047,000/);
  const hammondLocalSpend = page.locator(".economic-record").filter({ hasText: "Developer-reported cumulative spending with local contractors" });
  assert.match(await hammondLocalSpend.innerText(), /More than \$80,000,000[\s\S]*Existing Building 1/);
  assert.match(await page.locator(".economic-record-list").innerText(), /910\.85 million gallons \/ day[\s\S]*18\.202 million gallons \/ day/);
  assert.equal(await page.locator(".tif-revenue-history tbody tr").count(), 4);
  assert.match(await page.locator(".tif-revenue-history tbody tr").filter({ hasText: "2022" }).innerText(), /\$260,800[\s\S]*\$160,800[\s\S]*\$160,800/);
  assert.match(await page.locator(".tif-revenue-history tbody tr").filter({ hasText: "2024" }).innerText(), /\$522,816[\s\S]*\$258,200[\s\S]*\$320,987/);
  assert.equal(await page.locator(".tif-debt-history tbody tr").count(), 3);
  assert.match(await page.locator(".tif-debt-history tbody tr").filter({ hasText: "2022" }).innerText(), /\$0[\s\S]*\$321,600[\s\S]*\$8,040,000/);
  assert.match(await page.locator(".tif-debt-history tbody tr").filter({ hasText: "2024" }).innerText(), /\$165,000[\s\S]*\$317,700[\s\S]*\$7,810,000/);
  assert.match(await page.locator(".economic-history").filter({ hasText: "Remaining data-center bond principal and interest commitment over time" }).innerText(), /CY2022[\s\S]*\$12,074,400[\s\S]*CY2024[\s\S]*\$11,205,100/);
  assert.equal(await page.locator(".project-research-update").count(), 30);
  const hammondUpdates = (await page.locator(".project-research-update").allInnerTexts()).join("\n");
  assert.match(hammondUpdates, /State debt register shows the existing TIF bond but no separate EID debt/);
  assert.match(hammondUpdates, /Unsubmitted 2025 annual report blocks the debt-series extension/);
  assert.match(hammondUpdates, /2024 data-hall buildout adds dated construction-supply-chain evidence/);
  assert.match(hammondUpdates, /State contract table separates the incentive cap, payment status and job expectations/);
  assert.match(hammondUpdates, /Annual state reports bound when Hammond's incentive balances changed/);
  assert.match(hammondUpdates, /State portal verifies qualified investment and separates the sales-tax exemption/);
  assert.match(hammondUpdates, /Industrial-recovery credit reaches the portal's full certified amount/);
  assert.match(hammondUpdates, /Current EDGE record closes with a small certified amount and no realized-job proof/);
  assert.match(hammondUpdates, /County industry series adds a noncausal employment and payroll benchmark/);
  assert.match(hammondUpdates, /Quarterly local-labor submissions remain a public-evidence gap/);
  await page.getByRole("tab", { name: /Plans & forecasts/ }).click();
  assert.equal(await page.locator(".economic-record").count(), 10);
  const hammondPlans = await page.locator(".economic-record-list").innerText();
  assert.match(hammondPlans, /About \$40,000,000[\s\S]*About \$200,000,000[\s\S]*About \$88,656,629/);
  assert.equal((hammondPlans.match(/Up to \$3,415,000/g) || []).length, 2);
  assert.match(hammondPlans, /About 40 jobs/);
  assert.match(hammondPlans, /\$750,000[\s\S]*45 jobs[\s\S]*\$9,045,773\.82[\s\S]*\$239,530,500/);
  assert.match(await page.locator(".projection-note").innerText(), /Realized spending, jobs and abatements have not been verified/);
  await page.locator(".economic-accounts").screenshot({ path: path.join(out, "hammond-eid-forecasts-mobile.png") });
  await page.getByRole("tab", { name: /Modeled synthesis/ }).click();
  assert.equal(await page.locator(".modeled-record").count(), 43);
  assert.match(await page.locator(".modeled-note").innerText(), /not observed or audited/i);
  const hammondModels = await page.locator(".modeled-record-list").innerText();
  assert.match(hammondModels, /Modeled direct local-contractor spending envelope[\s\S]*\$100,000,000/);
  assert.match(hammondModels, /Modeled total construction job-years[\s\S]*874\.91 job-years/);
  assert.match(hammondModels, /Modeled total annual operating FTE[\s\S]*202\.61 FTE/);
  assert.match(hammondModels, /Modeled gross property-tax distribution total[\s\S]*\$751,127\.92/);
  assert.match(hammondModels, /Modeled annual facility electricity consumption[\s\S]*114,993,396 kWh \/ year/);
  assert.match(hammondModels, /Modeled descriptive county-industry employment pre\/post change[\s\S]*-30\.93%/);
  const hammondConstructionModel = page.locator(".modeled-record").filter({ hasText: "Modeled total construction job-years" });
  await hammondConstructionModel.locator("summary").click();
  assert.match(await hammondConstructionModel.innerText(), /Method:[\s\S]*Formula:[\s\S]*Sensitivity envelope:[\s\S]*Confidence:[\s\S]*Named parameters[\s\S]*Limitations[\s\S]*Prince William County Data Center Market Study/);
  await page.locator(".modeled-record-list").screenshot({ path: path.join(out, "hammond-modeled-synthesis-mobile.png") });
  await hammondConstructionModel.scrollIntoViewIfNeeded();
  await page.screenshot({ path: path.join(out, "hammond-modeled-synthesis-viewport-mobile.png") });
  const hammondCoverage = page.locator(".annual-account-coverage");
  assert.equal(await hammondCoverage.locator(".evidence-grid article").count(), 8);
  assert.match(await hammondCoverage.innerText(), /Capital investment[\s\S]*11 reported[\s\S]*4 forecast[\s\S]*1 modeled/);
  assert.match(await hammondCoverage.innerText(), /Construction jobs and payroll[\s\S]*0 reported[\s\S]*0 forecast[\s\S]*9 modeled/);
  assert.match(await hammondCoverage.innerText(), /Local suppliers and household spending[\s\S]*1 reported[\s\S]*0 forecast[\s\S]*2 modeled/);
  assert.match(await hammondCoverage.innerText(), /Electricity, water, and cooling[\s\S]*5 reported[\s\S]*0 forecast[\s\S]*7 modeled/);
  const hammondReadiness = page.locator(".analysis-readiness");
  assert.match(await hammondReadiness.innerText(), /Construction contribution[\s\S]*Modeled estimate available[\s\S]*11 reported · 4 forecast · 10 modeled/);
  assert.match(await hammondReadiness.innerText(), /Operating employment[\s\S]*Modeled estimates available[\s\S]*28 reported · 2 forecast · 12 modeled/);
  assert.match(await hammondReadiness.innerText(), /Local fiscal balance[\s\S]*Modeled account complete[\s\S]*59 reported · 4 forecast · 7 modeled/);
  assert.match(await hammondReadiness.innerText(), /Attributable economic effects[\s\S]*Causal model available[\s\S]*3 causal models/);
  await hammondCoverage.screenshot({ path: path.join(out, "hammond-annual-account-coverage-mobile.png") });
  await hammondReadiness.screenshot({ path: path.join(out, "hammond-analysis-readiness-mobile.png") });
  check("Hammond passes the full modeled county-account gate with sourced and synthesized records separate");
  await page.getByRole("tab", { name: /Reported activity/ }).click();
  await noOverflow();
  await hammondLocalSpend.screenshot({ path: path.join(out, "hammond-local-contractors-mobile.png") });
  await page.locator(".tax-billing-history").screenshot({ path: path.join(out, "hammond-tax-history-mobile.png") });
  await page.locator(".economic-accounts").screenshot({ path: path.join(out, "hammond-depth-evidence-mobile.png") });
  await page.locator(".economic-accounts").screenshot({ path: path.join(out, "hammond-financing-water-mobile.png") });
  await page.locator(".tif-revenue-history").screenshot({ path: path.join(out, "hammond-tif-reconciliation-mobile.png") });
  await page.locator(".tif-debt-history").screenshot({ path: path.join(out, "hammond-tif-debt-mobile.png") });
  await page.locator(".economic-history").filter({ hasText: "Fund investment cost basis" }).screenshot({ path: path.join(out, "hammond-investment-cost-basis-mobile.png") });
  await page.locator(".economic-history").filter({ hasText: "Private equipment line-of-credit balance" }).screenshot({ path: path.join(out, "hammond-private-financing-mobile.png") });
  await page.locator(".economic-history").filter({ hasText: "County data-processing and hosting employment over time" }).screenshot({ path: path.join(out, "hammond-cbp-employment-mobile.png") });
  await page.locator(".economic-record").filter({ hasText: "$28,369,398.27" }).filter({ hasText: "IEDC portal retrieval snapshot" }).screenshot({ path: path.join(out, "hammond-state-incentive-status-mobile.png") });
  await page.locator(".project-research-update").filter({ hasText: "State portal verifies qualified investment and separates the sales-tax exemption" }).screenshot({ path: path.join(out, "hammond-state-data-incentive-mobile.png") });
  await page.locator(".project-research-update").filter({ hasText: "Industrial-recovery credit reaches the portal's full certified amount" }).screenshot({ path: path.join(out, "hammond-irtc-status-mobile.png") });
  await page.locator(".project-research-update").filter({ hasText: "Current EDGE record closes with a small certified amount and no realized-job proof" }).screenshot({ path: path.join(out, "hammond-edge-closeout-mobile.png") });
  await page.locator(".project-research-update").filter({ hasText: "2024 data-hall buildout adds dated construction-supply-chain evidence" }).screenshot({ path: path.join(out, "hammond-supplier-roster-mobile.png") });
  await page.locator(".project-research-update").filter({ hasText: "State contract table separates the incentive cap, payment status and job expectations" }).screenshot({ path: path.join(out, "hammond-state-contract-mobile.png") });
  await page.locator(".project-research-update").filter({ hasText: "Annual state reports bound when Hammond's incentive balances changed" }).screenshot({ path: path.join(out, "hammond-incentive-timeline-mobile.png") });
  await page.locator(".project-research-update").filter({ hasText: "State debt register shows the existing TIF bond but no separate EID debt" }).screenshot({ path: path.join(out, "hammond-eid-debt-screen-mobile.png") });
  await page.locator(".project-research-update").filter({ hasText: "Quarterly local-labor submissions remain a public-evidence gap" }).screenshot({ path: path.join(out, "hammond-local-labor-gap-mobile.png") });
  check("Hammond preserves missing local-labor submissions as a public-evidence gap without solicitation");

  await page.goto(`${url}#/project/prj_study_im3_building_00364289074`);
  await page.getByRole("heading", { name: "Microsoft San Antonio", exact: true }).waitFor();
  await page.locator(".economic-record").first().waitFor();
  assert.equal(await page.locator(".economic-record").count(), 1);
  assert.match(await page.locator(".economic-record-list").innerText(), /Cumulative[\s\S]*More than \$840,000,000/);
  assert.equal(await page.locator(".history-bar-row").count(), 0);
  await page.getByRole("tab", { name: /Plans & forecasts/ }).click();
  assert.equal(await page.locator(".economic-record").count(), 5);
  assert.match(await page.locator(".economic-record-list").innerText(), /Source-estimated net municipal fiscal impact[\s\S]*\$56,319,724/);
  assert.equal(await page.locator(".fiscal-history").count(), 0);
  await noOverflow();
  check("cumulative investment and the city's modeled net fiscal forecast retain distinct timing and basis");

  await page.goto(`${url}#/project/prj_study_im3_building_00499403180`);
  await page.getByRole("heading", { name: "Economic evidence", exact: true }).waitFor();
  assert.match(await page.locator(".record-scope").innerText(), /Supporting infrastructure/);
  await page.locator(".economic-record summary").click();
  assert.match(await page.locator(".economic-record details").innerText(), /financing to Microsoft/);
  assert.equal(await page.locator(".history-bar-row").count(), 0);
  await noOverflow();
  check("water-reuse infrastructure cost preserves payer, system scope and non-annual timing");

  await page.goto(`${url}#/project/prj_study_im3_campus_00231769626`);
  await page.getByRole("heading", { name: "Economic evidence", exact: true }).waitFor();
  assert.equal(await page.locator(".tax-billing-history").count(), 2);
  assert.equal(await page.locator(".tax-billing-history tbody tr").count(), 6);
  const googleBill = page.locator(".tax-billing-history").filter({ hasText: "party 155421" });
  const designBill = page.locator(".tax-billing-history").filter({ hasText: "party 130136" });
  assert.match(await googleBill.innerText(), /\$1,119,239,550[\s\S]*\$1,813,378\.61/);
  assert.match(await designBill.innerText(), /\$2,300,544,270[\s\S]*\$3,009,750\.4/);
  assert.match(await designBill.innerText(), /not verified cash collected/);
  assert.doesNotMatch(await page.locator(".tax-billing-history").allTextContents().then(t => t.join(" ")), /FY202|Taxes collected/);
  assert.equal(await page.locator(".economic-record").count(), 13);
  await noOverflow();
  await designBill.screenshot({ path: path.join(out, "tax-billing-mobile.png") });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await designBill.screenshot({ path: path.join(out, "tax-billing-desktop.png") });
  check("tax bills retain two taxpayer accounts, source tax years and the distinction from cash receipts");

  await page.goto(`${url}#/project/prj_study_im3_campus_00578435601`);
  await page.getByRole("heading", { name: "Economic evidence", exact: true }).waitFor();
  await page.locator(".economic-history").getByText("$53,736,860 ↗", { exact: true }).waitFor();
  assert.equal(await page.locator(".history-bar-row").count(), 4);
  assert.match(await page.locator(".economic-history").innerText(), /Calendar years/);
  assert.match(await page.locator(".history-bar-row").nth(2).innerText(), /CY2024[\s\S]*\$53,736,860/);
  const widths = await page.locator(".history-bar-track > div").evaluateAll(nodes => nodes.map(n => parseFloat(n.style.width)));
  assert(widths[2] < widths[1] && widths[3] > widths[2]);
  await page.setViewportSize({ width: 390, height: 844 });
  await noOverflow();
  await page.locator(".economic-history").screenshot({ path: path.join(out, "calendar-tax-base-mobile.png") });
  check("calendar-year assessed values preserve the reported decline and later increase");

  for (const [id, text, count] of [
    ["campus_00009474864", /\$6,800,000/, 1],
    ["building_00844389014", /70 jobs/, 2],
  ]) {
    await page.goto(`${url}#/project/prj_study_im3_${id}`);
    await page.getByRole("heading", { name: "Economic evidence", exact: true }).waitFor();
    assert.equal(await page.getByRole("tab", { name: /Plans & forecasts/ }).getAttribute("aria-selected"), "true");
    assert.equal(await page.locator(".economic-record").count(), count);
    assert.match(await page.locator(".economic-record-list").innerText(), text);
    await page.getByRole("tab", { name: /Reported activity/ }).click();
    assert.equal(await page.locator(".economic-record").count(), 0);
    await noOverflow();
  }
  check("water contributions and original operating-job commitments remain forecasts");
  await page.goto(`${url}#/project/prj_study_im3_building_00052227492`);
  await page.getByRole("heading", { name: "Economic evidence", exact: true }).waitFor();
  assert.equal(await page.locator(".economic-record").count(), 9);
  assert.match(await page.locator(".economic-record h4").first().innerText(), /Local government/);
  assert.equal(await page.locator(".fiscal-history tbody tr").count(), 6);
  assert.equal(await page.locator(".fiscal-history tbody").getByText("Not collected", { exact: true }).count(), 6);
  assert.match(await page.locator(".fiscal-history").innerText(), /City of Chaska payments/);
  assert.doesNotMatch(await page.locator(".fiscal-history").innerText(), /County taxes|same county account/);
  assert.match(await page.locator(".fiscal-history tbody tr").last().innerText(), /FY2025[\s\S]*\$49,305/);
  assert.match(await page.locator(".economic-history").innerText(), /payable years/);
  assert.equal(await page.locator(".history-bar-row").count(), 3);
  assert.match(await page.locator(".history-bar-row").last().innerText(), /TY2025[\s\S]*\$19,775,100/);
  await noOverflow();
  await page.locator(".fiscal-history").screenshot({ path: path.join(out, "chaska-fiscal-mobile.png") });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await noOverflow();
  await page.locator(".economic-accounts").screenshot({ path: path.join(out, "chaska-evidence-desktop.png") });
  check("city rebates preserve missing receipts and separate payable-year property valuations");
  await page.goto(`${url}#/project/prj_study_im3_building_00172739953`);
  await page.getByRole("heading", { name: "Switch Las Vegas NAP7", exact: true }).waitFor();
  await page.getByText("10 sourced records · partial coverage", { exact: true }).waitFor();
  assert.equal(await page.locator(".economic-record").count(), 10);
  assert.equal(await page.locator(".economic-history").count(), 3);
  assert.equal(await page.locator(".history-bar-row").count(), 6);
  assert.match(await page.locator(".economic-history").allInnerTexts().then(rows => rows.join(" ")), /FY2026[\s\S]*\$87,755,603[\s\S]*FY2027[\s\S]*\$88,942,140/);
  assert.match(await page.locator(".economic-history").allInnerTexts().then(rows => rows.join(" ")), /CY2017[\s\S]*\$200,500,000[\s\S]*CY2018[\s\S]*\$134,200,000/);
  assert.match(await page.locator(".economic-record-list").innerText(), /Quarter ended 2021-03-31[\s\S]*\$23,400,000/);
  assert.match(await page.locator(".economic-record-list").innerText(), /Quarter ended 2021-12-31[\s\S]*\$49,500,000/);
  assert.equal(await page.locator(".project-research-update").count(), 2);
  assert.match(await page.locator(".project-research-update").allInnerTexts().then(rows => rows.join(" ")), /cannot be assigned to this location[\s\S]*resolves the mapped NAP7 building/);
  await page.setViewportSize({ width: 390, height: 844 });
  await noOverflow();
  await page.locator(".economic-accounts").screenshot({ path: path.join(out, "switch-las-vegas-evidence-mobile.png") });
  await page.setViewportSize({ width: 1440, height: 1000 });
  check("NAP7 parcel values and Core Campus capital expenditures retain separate scopes while the combined audit stays contextual");

  await page.goto(`${url}#/project/prj_study_im3_building_00838817907`);
  await page.getByRole("heading", { name: "TierPoint Charlotte CL4", exact: true }).waitFor();
  await page.getByText("42 sourced records · partial coverage", { exact: true }).waitFor();
  assert.equal(await page.locator(".economic-history").count(), 0);
  assert.equal(await page.locator(".tax-billing-history tbody tr").count(), 14);
  assert.match(await page.locator(".tax-billing-history tbody tr").first().innerText(), /2013[\s\S]*\$1,735,800[\s\S]*\$22,294\.61[\s\S]*\$22,294\.61/);
  assert.match(await page.locator(".tax-billing-history tbody tr").last().innerText(), /2026[\s\S]*\$12,003,100[\s\S]*\$94,308\.35[\s\S]*\$94,308\.35/);
  assert.match(await page.locator(".project-research-update").innerText(), /building predates the 2014 CL4 opening/);
  await page.setViewportSize({ width: 390, height: 844 });
  await noOverflow();
  await page.locator(".tax-billing-history").screenshot({ path: path.join(out, "tierpoint-cl4-tax-history-mobile.png") });
  await page.setViewportSize({ width: 1440, height: 1000 });
  check("TierPoint CL4 preserves the building owner's parcel assessments, bills and verified payments");

  await page.goto(`${url}#/project/prj_study_im3_building_00388148510`);
  await page.getByRole("heading", { name: "TierPoint / Windstream Little Rock", exact: true }).waitFor();
  await page.getByText("24 sourced records · partial coverage", { exact: true }).waitFor();
  assert.equal(await page.locator(".tax-billing-history tbody tr").count(), 16);
  assert.match(await page.locator(".tax-billing-history tbody tr").filter({ hasText: "2013" }).innerText(), /Not collected[\s\S]*Not collected[\s\S]*Not collected/);
  assert.match(await page.locator(".tax-billing-history tbody tr").filter({ hasText: "2016" }).innerText(), /Not collected[\s\S]*Not collected[\s\S]*Not collected/);
  assert.match(await page.locator(".tax-billing-history tbody tr").filter({ hasText: "2025" }).innerText(), /Not collected[\s\S]*\$82,440\.85[\s\S]*Not collected/);
  assert.match(await page.locator(".tax-billing-history tbody tr").filter({ hasText: "2026" }).innerText(), /\$1,396,547[\s\S]*Not collected[\s\S]*Not collected/);
  assert.match(await page.locator(".economic-record-list").innerText(), /County appraised property value[\s\S]*\$6,982,735/);
  assert.match(await page.locator(".project-research-update").innerText(), /building predates the 2012 opening/);
  await page.setViewportSize({ width: 390, height: 844 });
  await noOverflow();
  await page.locator(".tax-billing-history").screenshot({ path: path.join(out, "tierpoint-little-rock-tax-history-mobile.png") });
  await page.setViewportSize({ width: 1440, height: 1000 });
  check("TierPoint Little Rock preserves assessment gaps and the unpaid 2025 parcel charge");

  await page.goto(`${url}#/project/prj_study_im3_point_09190480200`);
  await page.getByRole("heading", { name: "Stream Houston I / The Woodlands", exact: true }).waitFor();
  await page.getByText("46 sourced records · partial coverage", { exact: true }).waitFor();
  assert.equal(await page.locator(".economic-record").count(), 46);
  assert.equal(await page.locator(".tax-billing-history").count(), 2);
  assert.equal(await page.locator(".tax-billing-history tbody tr").count(), 23);
  assert.equal(await page.locator(".economic-history").count(), 2);
  const streamReal = page.locator(".tax-billing-history").filter({ hasText: "Real-property parcel 9714-07-00103" });
  const streamPersonal = page.locator(".tax-billing-history").filter({ hasText: "business-personal-property account P454338" });
  const streamValues = await page.locator(".economic-history").allInnerTexts().then(rows => rows.join(" "));
  assert.match(streamValues, /TY2014[\s\S]*\$8,500,000[\s\S]*TY2025[\s\S]*\$15,200,000/);
  assert.match(streamValues, /TY2015[\s\S]*\$400,000[\s\S]*TY2025[\s\S]*\$550,000/);
  assert.match(await streamReal.innerText(), /2014[\s\S]*Not collected[\s\S]*\$216,520\.50/);
  assert.match(await streamReal.innerText(), /2025[\s\S]*Not collected[\s\S]*\$290,684\.50/);
  assert.match(await streamPersonal.innerText(), /2015[\s\S]*Not collected[\s\S]*\$9,942\.40/);
  assert.match(await streamPersonal.innerText(), /2025[\s\S]*Not collected[\s\S]*\$9,357\.15/);
  assert.match(await page.locator(".project-research-update").innerText(), /remain a separately labeled series/);
  await page.setViewportSize({ width: 390, height: 844 });
  await noOverflow();
  await streamReal.screenshot({ path: path.join(out, "stream-houston-tax-history-mobile.png") });
  await page.locator(".economic-history").first().screenshot({ path: path.join(out, "stream-houston-appraised-history-mobile.png") });
  await page.setViewportSize({ width: 1440, height: 1000 });
  check("Stream Houston preserves separate real-property and equipment values and paid-account histories");

  await page.goto(`${url}#/project/prj_study_im3_building_00377585075`);
  await page.getByRole("heading", { name: "EdgeConneX DET01, Southfield", exact: true }).waitFor();
  await page.getByText("48 sourced records · partial coverage", { exact: true }).waitFor();
  assert.equal(await page.locator(".economic-record").count(), 44);
  assert.equal(await page.locator(".tax-billing-history").count(), 3);
  assert.equal(await page.locator(".tax-billing-history tbody tr").count(), 19);
  assert.equal(await page.locator(".economic-history").count(), 2);
  const edgeReal = page.locator(".tax-billing-history").filter({ hasText: "real-property parcel 76-24-33-476-055" });
  const edgeIft = page.locator(".tax-billing-history").filter({ hasText: "Industrial Facilities Tax account 76-IP-13-000-088" });
  const edgePersonal = page.locator(".tax-billing-history").filter({ hasText: "former-IFT commercial-personal account 76-99-43-004-025" });
  assert.match(await edgeReal.innerText(), /2017[\s\S]*\$46,734\.82[\s\S]*\$46,734\.82/);
  assert.match(await edgeReal.innerText(), /2025[\s\S]*Not collected[\s\S]*\$137,034\.94[\s\S]*\$137,034\.94/);
  assert.match(await edgeIft.innerText(), /2016[\s\S]*Not collected[\s\S]*\$24,068\.73[\s\S]*\$24,068\.73/);
  assert.match(await edgePersonal.innerText(), /2020[\s\S]*Not collected[\s\S]*\$110,548\.82[\s\S]*\$110,548\.82/);
  const edgeValues = await page.locator(".economic-history").allInnerTexts().then(rows => rows.join(" "));
  assert.match(edgeValues, /TY2023[\s\S]*\$1,910,905[\s\S]*TY2025[\s\S]*\$2,004,700/);
  assert.match(edgeValues, /TY2023[\s\S]*\$2,107,780[\s\S]*TY2025[\s\S]*\$1,856,400/);
  assert.match(await page.locator(".project-research-update").innerText(), /former-IFT personal account begins showing nonzero tax in 2020/);
  await page.getByRole("tab", { name: /Plans & forecasts/ }).click();
  assert.equal(await page.locator(".economic-record").count(), 4);
  assert.match(await page.locator(".economic-record-list").innerText(), /\$16,251,600[\s\S]*\$18,935,500[\s\S]*27 jobs[\s\S]*\$67,000/);
  assert.match(await page.locator(".projection-note").innerText(), /Realized spending, jobs and abatements have not been verified/);
  await page.setViewportSize({ width: 390, height: 844 });
  await noOverflow();
  await page.locator(".economic-accounts").screenshot({ path: path.join(out, "edgeconnex-det01-forecasts-mobile.png") });
  await page.getByRole("tab", { name: /Reported activity/ }).click();
  await edgeReal.screenshot({ path: path.join(out, "edgeconnex-det01-tax-history-mobile.png") });
  await page.setViewportSize({ width: 1440, height: 1000 });
  check("EdgeConneX DET01 keeps real, IFT and former-IFT accounts separate from investment, job and wage forecasts");

  await page.goto(`${url}#/project/prj_study_im3_point_06685432442`);
  await page.getByRole("heading", { name: "Switch Citadel / Tahoe Reno 1", exact: true }).waitFor();
  await page.getByText("79 sourced records · 34 modeled syntheses", { exact: true }).waitFor();
  await page.getByRole("heading", { name: "Full modeled county account", exact: true }).waitFor();
  assert.equal(await page.locator(".economic-record").count(), 72);
  const storeyTaxHistories = page.locator(".tax-billing-history");
  const storeyRealTaxHistory = storeyTaxHistories.filter({ hasText: "NV RNO 1, LLC real-property parcel 005-012-23" });
  assert.equal(await storeyTaxHistories.locator("tbody tr").count(), 14);
  assert.match(await storeyTaxHistories.locator("tbody tr").filter({ hasText: "2019" }).innerText(), /\$10,956,667\.05[\s\S]*\$0[\s\S]*Not collected/);
  assert.match(await storeyTaxHistories.locator("tbody tr").filter({ hasText: "$125,198,623.90" }).innerText(), /\$125,198,623\.90[\s\S]*\$1,083,187\.19[\s\S]*\$1,083,187\.19/);
  assert.match(await storeyRealTaxHistory.innerText(), /\$2,239,229\.35[\s\S]*\$2,369,299\.77[\s\S]*\$2,381,598\.47/);
  assert.equal(await page.locator(".economic-history").count(), 3);
  assert.equal(await page.locator(".history-bar-row").count(), 25);
  assert.equal(await page.locator(".project-research-update").count(), 8);
  assert.match(await page.locator(".project-research-update").allInnerTexts().then(rows => rows.join(" ")), /resolves Switch personal property at the Citadel campus/);
  assert.match(await page.locator(".economic-record-list").innerText(), /\$356,000[\s\S]*More than \$2,000,000/);
  const storeyDonation = page.locator(".economic-record").filter({ hasText: "$356,000" });
  await page.getByRole("tab", { name: /Plans & forecasts/ }).click();
  assert.equal(await page.locator(".economic-record").count(), 7);
  assert.match(await page.locator(".economic-record-list").innerText(), /About \$1,000,000,000[\s\S]*\$1,386,677,024[\s\S]*\$100,000/);
  await page.getByRole("tab", { name: /Reported activity/ }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await noOverflow();
  await storeyDonation.screenshot({ path: path.join(out, "switch-storey-community-contribution-mobile.png") });
  await storeyTaxHistories.first().screenshot({ path: path.join(out, "switch-citadel-tax-history-mobile.png") });
  await storeyRealTaxHistory.screenshot({ path: path.join(out, "switch-citadel-real-property-tax-mobile.png") });
  await page.getByRole("tab", { name: /Modeled synthesis/ }).click();
  assert.equal(await page.locator(".modeled-record").count(), 34);
  const storeyModels = await page.locator(".modeled-record-list").innerText();
  assert.match(storeyModels, /Modeled documented cumulative capital floor[\s\S]*\$239,343,184/);
  assert.match(storeyModels, /Modeled annual operating payroll[\s\S]*\$11,202,186\.6 \/ year/);
  assert.match(storeyModels, /Modeled cumulative verified property tax paid[\s\S]*\$11,324,644\.79/);
  assert.match(storeyModels, /Modeled annual facility electricity[\s\S]*594,453\.6 MWh \/ year/);
  assert.match(storeyModels, /Storey County descriptive covered-employment change[\s\S]*11,632\.67 jobs/);
  await page.locator(".modeled-record").first().locator("summary").click();
  assert.match(await page.locator(".modeled-record").first().innerText(), /Formula:[\s\S]*Named parameters[\s\S]*Complete annual Citadel capital ledger/);
  await page.locator(".modeled-record-list").screenshot({ path: path.join(out, "switch-storey-modeled-synthesis-mobile.png") });
  const storeyCoverage = page.locator(".annual-account-coverage");
  assert.equal(await storeyCoverage.locator(".evidence-grid article").count(), 8);
  assert.match(await storeyCoverage.innerText(), /Capital investment[\s\S]*13 reported[\s\S]*2 forecast[\s\S]*3 modeled[\s\S]*Modeled documented cumulative capital floor/);
  assert.match(await storeyCoverage.innerText(), /Construction jobs and payroll[\s\S]*0 reported[\s\S]*0 forecast[\s\S]*5 modeled[\s\S]*Modeled direct construction job-years/);
  assert.match(await storeyCoverage.innerText(), /Electricity, water, and cooling[\s\S]*0 reported[\s\S]*0 forecast[\s\S]*6 modeled[\s\S]*Modeled onsite water use/);
  assert.match(await storeyCoverage.innerText(), /Local suppliers and household spending[\s\S]*0 reported[\s\S]*0 forecast[\s\S]*2 modeled/);
  const storeyReadiness = page.locator(".analysis-readiness");
  assert.match(await storeyReadiness.innerText(), /Construction contribution[\s\S]*Modeled estimate available[\s\S]*13 reported · 2 forecast · 8 modeled/);
  assert.match(await storeyReadiness.innerText(), /Operating employment[\s\S]*Modeled estimates available[\s\S]*2 reported · 2 forecast · 6 modeled/);
  assert.match(await storeyReadiness.innerText(), /Local fiscal balance[\s\S]*Modeled account complete[\s\S]*55 reported · 3 forecast · 9 modeled/);
  assert.match(await storeyReadiness.innerText(), /Attributable economic effects[\s\S]*Causal model available[\s\S]*3 causal models/);
  await storeyCoverage.screenshot({ path: path.join(out, "switch-storey-annual-account-coverage-mobile.png") });
  await storeyReadiness.screenshot({ path: path.join(out, "switch-storey-analysis-readiness-mobile.png") });
  await page.setViewportSize({ width: 1440, height: 1000 });
  check("Citadel passes the full modeled county-account gate with scope, provenance and causal limits visible");
  await page.goto(`${url}#/project/prj_study_im3_building_01073720208`);
  await page.getByRole("heading", { name: "Google Council Bluffs", exact: true }).waitFor();
  await page.locator(".economic-record").first().waitFor();
  assert.equal(await page.locator(".economic-record").count(), 3);
  assert.equal(await page.locator(".economic-history").count(), 0);
  assert.match(await page.locator(".economic-record-list").innerText(), /About \$96,600,000/);
  assert.match(await page.locator(".economic-record-list").innerText(), /Gable Corp[\s\S]*Questa LLC[\s\S]*Tetra LLC/);
  await page.getByRole("tab", { name: /Plans & forecasts/ }).click();
  assert.equal(await page.locator(".economic-record").count(), 2);
  assert.match(await page.locator(".economic-record-list").innerText(), /\$600,000,000[\s\S]*31 jobs/);
  assert.match(await page.locator(".projection-note").innerText(), /Realized spending, jobs and abatements have not been verified/);
  await page.setViewportSize({ width: 390, height: 844 });
  await noOverflow();
  await page.locator(".economic-accounts").screenshot({ path: path.join(out, "council-bluffs-evidence-mobile.png") });
  check("Council Bluffs taxpayer stocks stay separate from state award commitments");
  await page.goto(`${url}#/project/prj_study_im3_building_00472761713`);
  await page.getByRole("heading", { name: "Economic evidence", exact: true }).waitFor();
  assert.equal(await page.locator(".economic-record").count(), 7);
  assert.equal(await page.locator(".tax-billing-history tbody tr").count(), 4);
  assert.match(await page.locator(".tax-billing-history tbody tr").first().innerText(), /2022[\s\S]*\$102,000,000[\s\S]*\$2,011,440/);
  assert.match(await page.locator(".tax-billing-history tbody tr").last().innerText(), /2025[\s\S]*\$102,000,000[\s\S]*Not collected/);
  await page.locator(".economic-accounts .research-details summary").click();
  assert.match(await page.locator(".economic-accounts .research-details").innerText(), /Structured data and published layout checked/);
  assert.match(await page.locator(".project-research-update").innerText(), /Township record links NYSE to the assessed parcel/);
  await page.setViewportSize({ width: 390, height: 844 });
  await noOverflow();
  await page.locator(".tax-billing-history").screenshot({ path: path.join(out, "nyse-mahwah-tax-history-mobile.png") });
  check("NYSE parcel assessments and prior-year tax charges remain distinct with 2025 tax uncollected");
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto(`${url}#/project/prj_study_im3_building_00598261190`);
  await page.getByRole("heading", { name: "State Farm Olathe", exact: true }).waitFor();
  await page.getByText("25 sourced records · partial coverage", { exact: true }).waitFor();
  assert.equal(await page.locator(".economic-record").count(), 25);
  assert.equal(await page.locator(".tax-billing-history tbody tr").count(), 7);
  assert.equal(await page.locator(".tax-billing-history thead th").count(), 4);
  assert.match(await page.locator(".tax-billing-history tbody tr").last().innerText(), /2025[\s\S]*\$19,994,965[\s\S]*\$2,298,781\.14[\s\S]*\$2,298,781\.14/);
  assert.equal(await page.locator(".economic-history .history-bar-row").count(), 5);
  assert.match(await page.locator(".economic-history").innerText(), /TY2024[\s\S]*\$91,415,000/);
  assert.match(await page.locator(".economic-record-list").innerText(), /Estimated cumulative capital expenditure[\s\S]*About \$169,778,850/);
  assert.match(await page.locator(".project-research-update").innerText(), /County parcel links HMC ownership and the State Farm data center/);
  await page.setViewportSize({ width: 390, height: 844 });
  await noOverflow();
  await page.locator(".tax-billing-history").screenshot({ path: path.join(out, "state-farm-olathe-tax-history-mobile.png") });
  check("State Farm parcel values, bills, paid account totals and estimated cumulative capex stay distinct");
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto(`${url}#/project/prj_study_im3_building_00300974499`);
  await page.getByRole("heading", { name: "Economic evidence", exact: true }).waitFor();
  await page.getByText("80 sourced records · 27 modeled syntheses", { exact: true }).waitFor();
  await page.getByRole("heading", { name: "Full modeled county account", exact: true }).waitFor();
  assert.equal(await page.locator(".economic-record").count(), 76);
  assert.equal(await page.locator(".tax-billing-history").count(), 2);
  assert.equal(await page.locator(".tax-billing-history tbody tr").count(), 22);
  const appleEquipment = page.locator(".tax-billing-history").filter({ hasText: "Apple Inc. business personal property" });
  const appleReal = page.locator(".tax-billing-history").filter({ hasText: "Platypus Development LLC" });
  assert.match(await appleEquipment.innerText(), /2025[\s\S]*\$8,289,401[\s\S]*\$966,899\.82[\s\S]*\$966,899\.82/);
  assert.match(await appleEquipment.innerText(), /2026[\s\S]*\$15,036,685[\s\S]*Not collected[\s\S]*Not collected/);
  assert.match(await appleReal.innerText(), /2025[\s\S]*\$10,109,024[\s\S]*\$906,476\.10[\s\S]*\$906,476\.10/);
  assert.equal(await page.locator(".economic-history").count(), 3);
  const appleElectricity = page.locator(".economic-history").filter({ hasText: "Reported annual electricity use" });
  assert.equal(await appleElectricity.locator(".history-bar-row").count(), 9);
  assert.match(await appleElectricity.innerText(), /FY2017[\s\S]*45,000,000 kWh \/ year[\s\S]*FY2025[\s\S]*563,000,000 kWh \/ year/);
  assert.match(await page.locator(".economic-record-list").innerText(), /50 MW[\s\S]*4\.67 MW[\s\S]*\$32,991,875\.28[\s\S]*About \$2,000,000,000/);
  const appleUpdates = (await page.locator(".project-research-update").allInnerTexts()).join("\n");
  assert.match(appleUpdates, /Nine-year electricity series/);
  assert.match(appleUpdates, /separate Apple equipment from Apple-associated real estate/);
  await page.setViewportSize({ width: 390, height: 844 });
  await noOverflow();
  await appleEquipment.screenshot({ path: path.join(out, "apple-mesa-tax-history-mobile.png") });
  await appleElectricity.screenshot({ path: path.join(out, "apple-mesa-electricity-history-mobile.png") });
  await page.getByRole("tab", { name: /Plans & forecasts/ }).click();
  assert.equal(await page.locator(".economic-record").count(), 4);
  assert.match(await page.locator(".economic-record-list").innerText(), /\$2,000,000,000[\s\S]*150 jobs[\s\S]*Up to 500 jobs[\s\S]*\$25,000,000/);
  await page.locator(".economic-record-list").screenshot({ path: path.join(out, "apple-mesa-forecasts-mobile.png") });
  await page.getByRole("tab", { name: /Modeled synthesis/ }).click();
  assert.equal(await page.locator(".modeled-record").count(), 27);
  assert.match(await page.locator(".modeled-note").innerText(), /not observed or audited/i);
  const appleModels = await page.locator(".modeled-record-list").innerText();
  assert.match(appleModels, /Modeled onsite water use[\s\S]*109,322,072\.06 gallons \/ year/);
  assert.match(appleModels, /Modeled FTZ-area employment midpoint[\s\S]*125\.5 FTE/);
  assert.match(appleModels, /Modeled FTZ-area annual payroll[\s\S]*\$11,902,668\.85/);
  assert.match(appleModels, /Modeled IOC tax credits realized[\s\S]*\$12,500,000/);
  assert.match(appleModels, /Modeled FTZ export-duty avoidance[\s\S]*\$2,187,500/);
  assert.match(appleModels, /Modeled Apple-only employment allocation[\s\S]*121\.84 FTE/);
  assert.match(appleModels, /Modeled Apple-only annual payroll allocation[\s\S]*\$11,555,328\.21/);
  assert.match(appleModels, /Modeled annual electricity-cost benchmark[\s\S]*\$56,665,950/);
  assert.match(appleModels, /Modeled location-based gross electricity emissions[\s\S]*180,341\.25 metric tons CO₂e \/ year/);
  assert.match(appleModels, /Modeled cooling-treatment water-savings potential[\s\S]*16,398,310\.81 gallons \/ year/);
  await page.locator(".modeled-record").first().locator("summary").click();
  assert.match(await page.locator(".modeled-record").first().innerText(), /Method:[\s\S]*Formula:[\s\S]*Sensitivity envelope:[\s\S]*Confidence:[\s\S]*Named parameters[\s\S]*Limitations[\s\S]*Apple Environmental Progress Report 2026/);
  await page.locator(".modeled-record-list").screenshot({ path: path.join(out, "apple-mesa-modeled-synthesis-mobile.png") });
  const appleCoverage = page.locator(".annual-account-coverage");
  assert.equal(await appleCoverage.locator(".evidence-grid article").count(), 8);
  assert.match(await appleCoverage.innerText(), /Permanent jobs and compensation[\s\S]*0 reported[\s\S]*1 forecast[\s\S]*7 modeled[\s\S]*Modeled Apple-only employment allocation/);
  assert.match(await appleCoverage.innerText(), /Incentives and public costs[\s\S]*0 reported[\s\S]*1 forecast[\s\S]*6 modeled[\s\S]*Modeled FTZ property-tax reduction versus Class 1/);
  assert.match(await appleCoverage.innerText(), /Electricity, water, and cooling[\s\S]*11 reported[\s\S]*0 forecast[\s\S]*4 modeled[\s\S]*Modeled cooling-treatment water-savings potential/);
  const appleReadiness = page.locator(".analysis-readiness");
  assert.match(await appleReadiness.innerText(), /Construction contribution[\s\S]*Modeled estimate available[\s\S]*9 reported · 2 forecast · 3 modeled/);
  assert.match(await appleReadiness.innerText(), /Operating employment[\s\S]*Modeled estimates available[\s\S]*0 reported · 1 forecast · 9 modeled/);
  assert.match(await appleReadiness.innerText(), /Local fiscal balance[\s\S]*Modeled account complete[\s\S]*56 reported · 1 forecast · 7 modeled/);
  assert.match(await appleReadiness.innerText(), /Attributable economic effects[\s\S]*Causal model available[\s\S]*3 causal models/);
  await appleCoverage.screenshot({ path: path.join(out, "apple-mesa-annual-account-coverage-mobile.png") });
  await appleReadiness.screenshot({ path: path.join(out, "apple-mesa-analysis-readiness-mobile.png") });
  check("Apple Mesa annual-account coverage and analysis readiness reflect its reported, forecast and modeled evidence");
  check("Apple Mesa source records, forecasts and 27 labeled modeled syntheses remain distinct");
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto(`${url}#/project/prj_study_im3_building_00664938835`);
  await page.getByRole("heading", { name: "Expedient Milwaukee / Franklin", exact: true }).waitFor();
  await page.getByText("7 sourced records · partial coverage", { exact: true }).waitFor();
  assert.equal(await page.locator(".economic-record").count(), 6);
  assert.equal(await page.locator(".tax-billing-history tbody tr").count(), 3);
  assert.match(await page.locator(".tax-billing-history tbody tr").first().innerText(), /2024[\s\S]*\$3,856,900/);
  assert.match(await page.locator(".economic-record-list").innerText(), /\$3,856,900[\s\S]*\$580,190[\s\S]*\$250,132/);
  await page.setViewportSize({ width: 390, height: 844 });
  await noOverflow();
  await page.locator(".economic-accounts").screenshot({ path: path.join(out, "expedient-franklin-actuals-mobile.png") });
  await page.getByRole("tab", { name: /Plans & forecasts/ }).click();
  assert.equal(await page.locator(".economic-record").count(), 1);
  assert.match(await page.locator(".economic-record-list").innerText(), /12 jobs/);
  await page.locator(".economic-accounts").screenshot({ path: path.join(out, "expedient-franklin-evidence-mobile.png") });
  check("Expedient adaptive reuse keeps parcel stocks, permit values and the hiring plan separate");
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto(`${url}#/project/prj_study_im3_building_00888253616`);
  await page.getByRole("heading", { name: "NTT Silicon Valley SV1", exact: true }).waitFor();
  await page.getByText("4 sourced records · partial coverage", { exact: true }).waitFor();
  assert.equal(await page.locator(".economic-record").count(), 2);
  assert.match(await page.locator(".economic-record-list").innerText(), /\$159,579,996[\s\S]*\$83,066,779/);
  assert.match(await page.locator(".project-research-update").innerText(), /1150 Walsh Avenue[\s\S]*1160 Walsh Avenue/);
  await page.getByRole("tab", { name: /Plans & forecasts/ }).click();
  assert.equal(await page.locator(".economic-record").count(), 2);
  assert.match(await page.locator(".economic-record-list").innerText(), /Up to 40 jobs[\s\S]*173,752 gallons \/ year/);
  await page.setViewportSize({ width: 390, height: 844 });
  await noOverflow();
  await page.locator(".economic-accounts").screenshot({ path: path.join(out, "ntt-sv1-evidence-mobile.png") });
  check("NTT SV1 keeps assessment-appeal positions, job plans and water design estimates distinct");
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto(`${url}#/project/prj_study_im3_building_00903236619`);
  await page.getByRole("heading", { name: "Quicken Loans Technology Center, Corktown", exact: true }).waitFor();
  await page.getByText("4 sourced records · partial coverage", { exact: true }).waitFor();
  assert.equal(await page.locator(".economic-record").count(), 4);
  assert.equal(await page.locator(".economic-history").count(), 2);
  assert.match(await page.locator(".economic-history").nth(0).innerText(), /CY2025[\s\S]*\$3,298,400[\s\S]*CY2026[\s\S]*\$3,643,800/);
  assert.match(await page.locator(".economic-history").nth(1).innerText(), /CY2025[\s\S]*\$2,679,332[\s\S]*CY2026[\s\S]*\$2,813,298/);
  assert.match((await page.locator(".project-research-update").allInnerTexts()).join("\n"), /whole-parcel stocks[\s\S]*partial-building tenancy[\s\S]*zero-water cooling claim remains unmetered/i);
  await page.setViewportSize({ width: 390, height: 844 });
  await noOverflow();
  await page.locator(".economic-accounts").screenshot({ path: path.join(out, "quicken-corktown-evidence-mobile.png") });
  check("Quicken Corktown keeps whole-parcel values separate from partial-building tenancy and water claims");
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(`${url}#/study`);
  await page.getByLabel("Search projects").waitFor();
  await noOverflow();
  await page.screenshot({ path: path.join(out, "register-mobile.png") });
  check("project and register at mobile width");

  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.evaluate(() => performance.clearResourceTimings());
  await page.goto(`${url}#/map`);
  await page.locator("canvas").waitFor();
  await page.waitForFunction(() => !document.querySelector(".map-message") && !document.querySelector(".map-loading"), undefined, { timeout: 45000 });
  assert.match(await page.locator(".review-key").innerText(), /full modeled accounts \(3\)/i);
  assert.doesNotMatch(await page.locator(".legend").innerText(), /IM3|pending|merged|queued/i);
  await page.getByLabel("Completed project markers").selectOption("Colocation");
  assert.match(await page.locator(".review-key").innerText(), /full modeled accounts \(2\)/i);
  await page.getByLabel("Completed project markers").selectOption("");
  await page.screenshot({ path: path.join(out, "map-desktop.png") });
  assert.doesNotMatch(await page.locator(".sidebar").innerText(), /Source records|Building records|Campus records|Observed footprint|First-entry research/i);
  const mapResources = await page.evaluate(() => performance.getEntriesByType("resource").map(entry => entry.name));
  assert.equal(mapResources.some(name => name.endsWith("/data/v1/maps/facilities.geojson")), false);
  assert.equal(mapResources.some(name => name.includes("/data/v1/counties/")), false);
  assert.equal(mapResources.some(name => name.includes("/data/v1/panels/county-economic-history/")), false);
  const response = await page.request.get(`${url}data/v1/study/index.json`);
  const study = await response.json();
  assert.equal(study.projects.length, 36);
  assert.equal(study.projects.filter(p => p.model_completeness.status === "full_modeled_account").length, 3);
  const target = study.projects.find(p => p.name === "Apple Mesa");
  const canvas = await page.locator("canvas").boundingBox();
  const world = 512 * 2 ** 3.25;
  const mercatorY = lat => (1 - Math.asinh(Math.tan(lat * Math.PI / 180)) / Math.PI) / 2;
  await page.mouse.click(canvas.x + canvas.width / 2 + (target.longitude + 98.5) / 360 * world,
    canvas.y + canvas.height / 2 + (mercatorY(target.latitude) - mercatorY(38.5)) * world);
  await page.waitForURL(`**/project/${target.project_id}`);
  await page.getByRole("heading", { name: "Sources & research history" }).waitFor();
  check("map renders only three completed studies while preserving the 36-project register off-map");

  await page.goto(`${url}#/project/prj_study_missing`);
  await page.getByRole("heading", { name: "Project or page not found" }).waitFor();
  await page.getByRole("link", { name: "Evidence & methodology", exact: true }).click();
  await page.getByRole("heading", { name: "County first entry remains a specific question" }).waitFor();
  check("unknown project and methodology navigation");

  assert.deepEqual(errors, [], "browser runtime errors");
  await writeFile(path.join(out, "browser-checks.json"), JSON.stringify({ url, checks, runtime_errors: errors }, null, 2) + "\n");
} finally {
  await browser.close();
}
