// Browser checks against a running preview. Set PLAYWRIGHT_MODULE when using a bundled runtime.
import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || "playwright");
const url = process.env.STUDY_PREVIEW_URL || "http://127.0.0.1:5173/";
const out = path.resolve(process.env.STUDY_BROWSER_REPORT_DIR || "reports/application-remediation");
await mkdir(out, { recursive: true });
const browser = await chromium.launch({ headless: true, args: ["--enable-unsafe-swiftshader"] });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
const errors = [];
const checks = [];
page.on("pageerror", error => errors.push(error.message));
page.setDefaultTimeout(20000);
const check = name => { checks.push(name); console.log(`PASS ${name}`); };
const noOverflow = async () => {
  const result = await page.evaluate(() => ({
    fits: document.documentElement.scrollWidth <= innerWidth,
    viewport: innerWidth,
    documentWidth: document.documentElement.scrollWidth,
    offenders: [...document.querySelectorAll("body *")]
      .filter(element => element.getBoundingClientRect().right > innerWidth + 1)
      .slice(0, 8)
      .map(element => ({ tag: element.tagName, className: element.className, text: element.textContent?.trim().slice(0, 120) })),
    wideElements: [...document.querySelectorAll("body *")]
      .filter(element => element.scrollWidth > innerWidth)
      .sort((a, b) => b.scrollWidth - a.scrollWidth)
      .slice(0, 8)
      .map(element => ({ tag: element.tagName, className: element.className, scrollWidth: element.scrollWidth, clientWidth: element.clientWidth })),
  }));
  assert(result.fits, `horizontal overflow: ${JSON.stringify(result)}`);
};
const openDetails = async selector => {
  const details = page.locator(selector).first();
  await details.waitFor();
  if (await details.getAttribute("open") === null) await details.locator(":scope > summary").click();
};

try {
  await page.goto(url, { waitUntil: "domcontentloaded" });
  await page.getByRole("heading", { name: "Project register", exact: true }).waitFor();
  assert.equal(await page.locator(".project-card").count(), 36);
  const themeColors = await page.evaluate(() => ({
    body: getComputedStyle(document.body).backgroundColor,
    topbar: getComputedStyle(document.querySelector(".topbar")).backgroundColor,
    card: getComputedStyle(document.querySelector(".project-card")).backgroundColor,
  }));
  assert.deepEqual(themeColors, { body: "rgb(8, 10, 15)", topbar: "rgb(8, 9, 14)", card: "rgb(14, 18, 24)" });
  await noOverflow();
  await page.screenshot({ path: path.join(out, "register-desktop.png") });
  check("register shows 36 candidates without overflow");
  check("dark map-forward theme applies to the application shell and research cards");

  await page.getByLabel("Economic evidence", { exact: true }).selectOption("available");
  assert.equal(await page.locator(".project-card").count(), 36);
  await page.getByLabel("Economic evidence", { exact: true }).selectOption("missing");
  assert.equal(await page.locator(".project-card").count(), 0);
  await page.getByRole("heading", { name: "No matching projects" }).waitFor();
  await page.getByRole("button", { name: "Clear filters" }).click();
  check("economic coverage filter reports evidence on all 36 candidates");

  await page.getByLabel("Project type", { exact: true }).selectOption("Private enterprise");
  assert.equal(await page.locator(".project-card").count(), 3);
  await page.getByLabel("State", { exact: true }).selectOption("MI");
  assert.equal(await page.locator(".project-card").count(), 1);
  await page.getByRole("link", { name: "Quicken Loans Technology Center, Corktown", exact: true }).click();
  await page.getByRole("heading", { name: "Sources & research history" }).waitFor();
  assert.equal(await page.locator(".facility-evidence-summary").isVisible(), true);
  assert.match(await page.locator(".facility-evidence-summary").innerText(), /Tax base and revenue[\s\S]*\$3,643,800[\s\S]*\$2,813,298/i);
  assert.equal(await page.locator(".evidence-ledger").getAttribute("open"), null);
  await page.locator(".facility-evidence-summary").screenshot({ path: path.join(out, "facility-evidence-summary-desktop.png") });
  await page.setViewportSize({ width: 390, height: 844 });
  await noOverflow();
  await page.locator(".facility-evidence-summary").screenshot({ path: path.join(out, "facility-evidence-summary-mobile.png") });
  await page.setViewportSize({ width: 1440, height: 1000 });
  assert.equal(await page.locator(".annual-account-coverage").count(), 0);
  assert.equal(await page.locator(".analysis-readiness").count(), 0);
  await openDetails(".evidence-ledger");
  assert.equal(await page.getByRole("tab", { name: /Reported activity/ }).isVisible(), true);
  check("combined filters and enterprise profile preserve partial economic coverage");

  await page.getByRole("link", { name: "Project study", exact: true }).click();
  await page.getByLabel("Search projects").fill("zzzz-no-project");
  await page.getByRole("heading", { name: "No matching projects" }).waitFor();
  await page.getByRole("button", { name: "Clear filters" }).click();
  assert.equal(await page.locator(".project-card").count(), 36);
  await page.getByLabel("Historical evidence", { exact: true }).selectOption("needs_research");
  assert.equal(await page.locator(".project-card").count(), 3);
  await page.getByRole("link", { name: "Google Lenoir", exact: true }).click();
  await page.getByRole("heading", { name: "Sources & research history" }).waitFor();
  assert.match(await page.locator(".project-tags").innerText(), /Campus-linked project/);
  await page.locator(".media-timeline").waitFor({ state: "attached" });
  assert.equal(await page.locator(".media-timeline > li").count(), 7);
  assert.match(await page.locator(".media-timeline").innerText(), /announces a Lenoir data center[\s\S]*opens the first Lenoir data center[\s\S]*further growth/i);
  check("empty state, reset and reconstructed campus chronology");

  await page.goto(`${url}#/project/prj_study_im3_building_00438078069`);
  await openDetails(".evidence-ledger");
  await page.getByRole("heading", { name: "Sources & research history" }).waitFor();
  assert.match(await page.locator(".facility-evidence-summary").innerText(), /Construction[\s\S]*Peak construction workforce[\s\S]*1,300 workers/i);
  assert.equal(await page.locator(".facility-evidence-table tbody tr").count(), 1);
  await page.getByText("Inventory identity and earlier first-entry research", { exact: true }).click();
  assert.match(await page.locator(".research-details").filter({ hasText: "Inventory identity and earlier first-entry research" }).innerText(), /cannot be the county's first entry/);
  await page.getByRole("link", { name: /Polk County, IA · View county account/ }).click();
  await page.getByRole("heading", { name: "Polk County", exact: true }).waitFor();
  await page.getByRole("link", { name: /Meta Altoona/ }).waitFor();
  assert.equal(await page.locator(".profile-grid").getByText("County first-entry treatment").count(), 0);
  check("incomplete facility pages put structured source evidence ahead of the collapsed audit ledger");
  check("rejected first-entry candidate remains accessible through existing county route");

  await page.goto(`${url}#/project/prj_study_im3_building_00116005354`);
  await openDetails(".evidence-ledger");
  await page.getByRole("heading", { name: "Economic evidence", exact: true }).waitFor();
  assert.equal(await page.locator(".history-bar-row").count(), 23);
  assert.equal(await page.locator(".history-bar-row.uncollected").count(), 5);
  assert.equal(await page.locator(".economic-record").count(), 34);
  assert.match(await page.locator(".economic-history").first().innerText(), /\$1,476,648,949/);
  await page.locator(".economic-record summary").first().click();
  assert.match(await page.locator(".economic-record").first().innerText(), /tax-base stock, not tax receipts/);
  assert.match(await page.locator(".economic-record details a").first().getAttribute("href"), /#page=242$/);
  await page.locator(".economic-accounts").scrollIntoViewIfNeeded();
  await noOverflow();
  await page.screenshot({ path: path.join(out, "economic-history-desktop.png") });
  await page.setViewportSize({ width: 390, height: 844 });
  await noOverflow();
  await page.locator(".economic-history").first().screenshot({ path: path.join(out, "economic-history-mobile.png") });
  check("tax-base history shows missing years, county scope and page-level sources on desktop/mobile");

  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto(`${url}#/project/prj_study_im3_building_00464097467`);
  await openDetails(".evidence-ledger");
  await page.getByRole("tab", { name: /Reported activity/ }).waitFor();
  await page.locator(".account-count").getByText("21 sourced records · 7 modeled syntheses", { exact: true }).waitFor();
  await page.locator(".economic-record-list").getByText("80 FTE", { exact: true }).waitFor();
  assert.equal(await page.locator(".economic-record").count(), 15);
  assert.match(await page.locator(".economic-record-list").innerText(), /80 FTE[\s\S]*83 employees[\s\S]*250 MW[\s\S]*422,000,000 kWh \/ year/);
  assert.doesNotMatch(await page.locator(".economic-record-list").innerText(), /742,071,428/);
  await page.getByRole("tab", { name: /Reported activity/ }).focus();
  await page.keyboard.press("ArrowRight");
  assert.equal(await page.getByRole("tab", { name: /Plans & forecasts/ }).getAttribute("aria-selected"), "true");
  assert.equal(await page.locator(".economic-record").count(), 6);
  assert.match(await page.locator(".economic-record-list").innerText(), /\$742,071,428[\s\S]*\$163,000,000[\s\S]*\$200,909,110/);
  assert.match(await page.locator(".economic-record-list").innerText(), /10-year estimate/);
  assert.equal(await page.locator(".history-bar-row").count(), 0);
  await page.locator(".economic-accounts").scrollIntoViewIfNeeded();
  await page.screenshot({ path: path.join(out, "economic-forecasts-desktop.png") });
  await page.setViewportSize({ width: 390, height: 844 });
  await noOverflow();
  await page.locator(".economic-accounts").screenshot({ path: path.join(out, "economic-forecasts-mobile.png") });
  await page.getByRole("tab", { name: /Modeled synthesis/ }).click();
  assert.equal(await page.locator(".modeled-record").count(), 7);
  assert.match(await page.locator(".modeled-record-list").innerText(), /Modeled construction-eligible expansion spending[\s\S]*\$163,000,000[\s\S]*Modeled annualized direct operating payroll[\s\S]*\$7,057,232/);
  await page.setViewportSize({ width: 1440, height: 1000 });
  check("actual workforce and forecasts stay separate with distinct horizons and keyboard navigation");

  await page.goto(`${url}#/project/prj_study_im3_point_06685432442`);
  await openDetails(".evidence-ledger");
  await page.getByRole("heading", { name: "Economic evidence", exact: true }).waitFor();
  await page.locator(".account-count").getByText("86 sourced records · 4 modeled syntheses", { exact: true }).waitFor();
  await openDetails(".project-research-ledger");
  assert.match(await page.locator(".economic-record-list").innerText(), /324 employees[\s\S]*\$50\.97 \/ hour[\s\S]*\$452,372,959/);
  const switchAudit = page.locator(".economic-record").filter({ hasText: "State-audited capital expenditure" });
  await switchAudit.locator("summary").click();
  assert.match(await switchAudit.innerText(), /Company \/ county context[\s\S]*unallocated to Tahoe Reno 1/);
  assert.match(await switchAudit.locator("a").getAttribute("href"), /NRS-231\.0685-GOED-Biennial-Report-2023-24\.pdf#page=66$/);
  assert.match(await page.locator(".project-research-update").filter({ hasText: "GOED audit revision" }).innerText(), /supersed/i);
  await page.setViewportSize({ width: 390, height: 844 });
  await noOverflow();
  await switchAudit.screenshot({ path: path.join(out, "switch-storey-audit-capex-mobile.png") });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.getByRole("tab", { name: /Plans & forecasts/ }).click();
  assert.equal(await page.locator(".economic-record").count(), 8);
  assert.match(await page.locator(".economic-record-list").innerText(), /50 jobs[\s\S]*\$28\.98 \/ hour[\s\S]*\$1,386,677,024[\s\S]*\$75,720,025[\s\S]*\$32,095,728[\s\S]*\$100,000/);
  await page.setViewportSize({ width: 390, height: 844 });
  await noOverflow();
  await page.locator(".economic-accounts").screenshot({ path: path.join(out, "switch-storey-agreement-forecasts-mobile.png") });
  await page.setViewportSize({ width: 1440, height: 1000 });
  check("Switch Storey audit outcomes remain separate from agreement forecasts and building allocation");

  await page.goto(`${url}#/project/prj_study_im3_building_01132541700`);
  await openDetails(".evidence-ledger");
  await page.getByRole("heading", { name: "Economic evidence", exact: true }).waitFor();
  await page.locator(".economic-record").first().waitFor();
  assert.equal(await page.locator(".economic-record").count(), 10);
  assert.match(await page.locator(".economic-record-list").innerText(), /More than 1,500 workers/);
  assert.match(await page.locator(".economic-record-list").innerText(), /Historical construction peak reported 2020-08-05/);
  assert.match(await page.locator(".economic-record-list").innerText(), /\$4,200,000/);
  assert.match(await page.locator(".economic-record-list").innerText(), /948,859,000 kWh/);
  await page.locator(".economic-record summary").first().click();
  assert.doesNotMatch(await page.locator(".economic-record details").first().innerText(), /PDF page|undefined/);
  assert.equal(await page.locator(".economic-record details a").first().getAttribute("href"), "https://datacenters.atmeta.com/2020/08/henrico-county-we-are-online/");
  await page.getByRole("tab", { name: /Plans & forecasts/ }).click();
  assert.equal(await page.locator(".economic-record").count(), 3);
  assert.match(await page.locator(".economic-record-list").innerText(), /More than \$1,000,000,000/);
  assert.match(await page.locator(".economic-record-list").innerText(), /completion date unspecified/);
  await page.setViewportSize({ width: 390, height: 844 });
  await noOverflow();
  await page.locator(".economic-accounts").screenshot({ path: path.join(out, "qualified-plans-mobile.png") });
  check("qualified peaks and completion-dependent plans preserve wording and HTML source links");

  await page.goto(`${url}#/project/prj_study_im3_building_00397914434`);
  await openDetails(".evidence-ledger");
  await page.getByRole("heading", { name: "Economic evidence", exact: true }).waitFor();
  assert.match(await page.locator(".economic-record-list").innerText(), /2023 source table/);
  assert.match(await page.locator(".record-value").first().innerText(), /\$10,375,490/);
  assert.equal(await page.locator(".history-bar-row").count(), 24);
  await noOverflow();
  await page.setViewportSize({ width: 1440, height: 1000 });
  check("county source-year value remains distinct from a fiscal-year series");

  await page.goto(`${url}#/project/prj_study_im3_building_00610827836`);
  await openDetails(".evidence-ledger");
  await page.getByRole("heading", { name: "Economic evidence", exact: true }).waitFor();
  assert.equal(await page.getByRole("tab", { name: /Plans & forecasts/ }).getAttribute("aria-selected"), "true");
  assert.match(await page.locator(".economic-record-list").innerText(), /\$1,300,000,000/);
  await page.getByRole("tab", { name: /Reported activity/ }).click();
  assert.equal(await page.locator(".economic-record").count(), 0);
  assert.match(await page.locator("#economic-records").innerText(), /No reported activity collected/);
  check("a forecast-only project never displays its plan as reported activity");

  await page.goto(`${url}#/project/prj_study_im3_building_00460089167`);
  await openDetails(".evidence-ledger");
  await page.getByRole("heading", { name: "Sources & research history" }).waitFor();
  await page.locator(".account-status").getByText("Research complete · analytical gaps remain", { exact: true }).waitFor();
  await page.locator(".account-count").getByText("28 sourced records · 6 modeled syntheses", { exact: true }).waitFor();
  await openDetails(".evidence-ledger");
  await openDetails(".project-research-ledger");
  await page.locator(".fiscal-history").waitFor();
  assert.equal(await page.locator(".fiscal-history tbody tr").count(), 5);
  assert.equal(await page.locator(".history-bar-row").count(), 5);
  assert.equal(await page.locator(".economic-record").count(), 25);
  assert.equal(await page.locator(".fiscal-history thead th").count(), 4);
  assert.match(await page.locator(".fiscal-history").innerText(), /\$6,573,472/);
  assert.match(await page.locator(".fiscal-history").innerText(), /\$6,082,555/);
  assert.match(await page.locator(".fiscal-history").innerText(), /provisional/);
  assert.match(await page.locator(".fiscal-history tbody tr").first().innerText(), /FY2021[\s\S]*6,573,472[\s\S]*6,082,555[\s\S]*490,917/);
  assert.match(await page.locator(".fiscal-history tbody tr").last().innerText(), /FY2025[\s\S]*3,901,427[\s\S]*3,582,303[\s\S]*319,124/);
  assert.match(await page.locator(".economic-record-list").innerText(), /At least \$750,000,000[\s\S]*At least 275 jobs[\s\S]*At least \$6,400,000[\s\S]*\$148,900/);
  assert.match(await page.locator(".project-research-update").allInnerTexts().then(rows => rows.join(" ")), /operator factsheet broadens[\s\S]*water-line grant[\s\S]*Brownfield reuse/i);
  await page.locator(".fiscal-history").screenshot({ path: path.join(out, "fiscal-comparison-desktop.png") });
  await page.screenshot({ path: path.join(out, "project-desktop.png") });
  await page.setViewportSize({ width: 390, height: 844 });
  await noOverflow();
  await page.locator(".fiscal-history").screenshot({ path: path.join(out, "fiscal-comparison-mobile.png") });
  await page.screenshot({ path: path.join(out, "project-mobile.png") });
  await page.locator(".economic-accounts").screenshot({ path: path.join(out, "meta-forest-city-depth-mobile.png") });
  await page.getByRole("tab", { name: /Plans & forecasts/ }).click();
  assert.equal(await page.locator(".economic-record").count(), 3);
  assert.match(await page.locator(".economic-record-list").innerText(), /10 jobs[\s\S]*About \$450,000,000[\s\S]*More than 250 workers/);
  check("Forest City depth account separates fiscal arithmetic, current operator claims and original forecasts");

  await page.goto(`${url}#/project/prj_study_im3_building_00978934687`);
  await openDetails(".evidence-ledger");
  await page.getByRole("heading", { name: "Digital Crossroad DX-1, Hammond", exact: true }).waitFor();
  await page.locator(".account-status").getByText("Research complete · analytical gaps remain", { exact: true }).waitFor();
  await openDetails(".project-research-ledger");
  await page.getByRole("heading", { name: "Proposed expansion agreement expired" }).waitFor();
  const hammondExpiry = page.locator(".project-research-update").filter({ hasText: "Proposed expansion agreement expired" });
  assert.match(await hammondExpiry.innerText(), /2026-07-01/);
  assert.match(await hammondExpiry.innerText(), /does not establish closure/);
  await page.locator(".account-count").getByText("129 sourced records · 2 modeled syntheses", { exact: true }).waitFor();
  assert.equal(await page.locator(".economic-record").count(), 119);
  assert.equal(await page.locator(".tax-billing-history tbody tr").count(), 7);
  const hammondRealTax = page.locator(".tax-billing-history").filter({ hasText: "leasehold parcel" });
  const hammondPersonalTax = page.locator(".tax-billing-history").filter({ hasText: "personal-property account" });
  assert.match(await hammondRealTax.locator("tbody tr").nth(3).innerText(), /2024[\s\S]*\$19,987,700[\s\S]*\$641,685\.14[\s\S]*\$641,685\.14/);
  assert.match(await hammondRealTax.locator("tbody tr").last().innerText(), /2025[\s\S]*\$20,014,600[\s\S]*\$640,867\.48[\s\S]*Not collected/);
  assert.match(await page.locator(".economic-record-list").innerText(), /Account property taxes paid[\s\S]*\$320,433\.74/);
  assert.match(await hammondPersonalTax.innerText(), /2024[\s\S]*\$31,801,980[\s\S]*\$1,020,970\.76[\s\S]*\$1,020,970\.76/);
  assert.match(await hammondPersonalTax.innerText(), /2025[\s\S]*\$29,673,490[\s\S]*\$950,145\.14[\s\S]*Not collected/);
  assert.equal(await page.locator(".economic-record").filter({ hasText: "Account property taxes paid" }).filter({ hasText: "$475,072.57" }).count(), 1);
  assert.match(await page.locator(".economic-record-list").innerText(), /Local property-tax credits[\s\S]*\$95,115\.62/);
  assert.match(await page.locator(".economic-record-list").innerText(), /More than \$50,000,000[\s\S]*\$30,328,680[\s\S]*20 MW[\s\S]*8 generators/);
  assert.match(await page.locator(".economic-record-list").innerText(), /\$211,110,564[\s\S]*\$220,812,911[\s\S]*\$240,300,000[\s\S]*\$249,400,000/);
  assert.match(await page.locator(".economic-record-list").innerText(), /15 MW/);
  assert.match(await page.locator(".economic-record-list").innerText(), /\$7,745,144[\s\S]*\$7,263,439[\s\S]*115,652 square feet[\s\S]*89\.3%/);
  assert.equal(await page.locator(".economic-record").filter({ hasText: "State incentive paid or certified to date" }).count(), 14);
  assert.match(await page.locator(".economic-record-list").innerText(), /\$0[\s\S]*\$9,045,773\.82[\s\S]*\$28,369,398\.27[\s\S]*\$186,954,143[\s\S]*Public infrastructure grant[\s\S]*\$8,000/);
  assert.match(await page.locator(".economic-record-list").innerText(), /\$11,763[\s\S]*State incentive downward adjustment[\s\S]*\$5,209/);
  assert.match(await page.locator(".economic-record-list").innerText(), /IEDC 2021 EICR, cumulative project 419942 edge, paid\/certified to date[\s\S]*IEDC 2023 EICR, cumulative project 419942 edge, paid\/certified to date/);
  assert.match(await page.locator(".economic-record-list").innerText(), /IEDC 2021 EICR, cumulative project 419963 irtc, paid\/certified to date[\s\S]*IEDC 2025 EICR, cumulative project 419963 irtc, paid\/certified to date/);
  assert.match(await page.locator(".economic-record-list").innerText(), /IEDC 2023 EICR, cumulative project 419963 data, paid\/certified to date[\s\S]*IEDC 2025 EICR, cumulative project 419963 data, paid\/certified to date/);
  assert.match(await page.locator(".economic-record-list").innerText(), /17 employees[\s\S]*\$8,040,000/);
  assert.match(await page.locator(".economic-record-list").innerText(), /County data-processing and hosting establishments[\s\S]*7 establishments[\s\S]*County data-processing and hosting employment[\s\S]*67 employees/);
  assert.match(await page.locator(".economic-record-list").innerText(), /County industry context[\s\S]*entire six-digit industry, not Digital Crossroad or Hammond alone/);
  assert.match(await page.locator(".economic-history").filter({ hasText: "County data-processing and hosting employment over time" }).innerText(), /2016[\s\S]*67 employees[\s\S]*2021[\s\S]*429 employees[\s\S]*2023[\s\S]*44 employees/);
  assert.match(await page.locator(".economic-history").filter({ hasText: "County data-processing and hosting annual payroll over time" }).innerText(), /CY2016[\s\S]*\$7,295,000[\s\S]*CY2023[\s\S]*\$4,047,000/);
  const hammondLocalSpend = page.locator(".economic-record").filter({ hasText: "Developer-reported cumulative spending with local contractors" });
  assert.match(await hammondLocalSpend.innerText(), /More than \$80,000,000[\s\S]*Existing Building 1/);
  assert.match(await page.locator(".economic-record-list").innerText(), /18\.202 million gallons \/ day[\s\S]*910\.08 million gallons \/ day/);
  assert.equal(await page.locator(".tif-revenue-history tbody tr").count(), 4);
  assert.match(await page.locator(".tif-revenue-history tbody tr").filter({ hasText: "2022" }).innerText(), /\$260,800[\s\S]*\$160,800[\s\S]*\$160,800/);
  assert.match(await page.locator(".tif-revenue-history tbody tr").filter({ hasText: "2024" }).innerText(), /\$522,816[\s\S]*\$258,200[\s\S]*\$320,987/);
  assert.equal(await page.locator(".tif-debt-history tbody tr").count(), 3);
  assert.match(await page.locator(".tif-debt-history tbody tr").filter({ hasText: "2022" }).innerText(), /\$0[\s\S]*\$321,600[\s\S]*\$8,040,000/);
  assert.match(await page.locator(".tif-debt-history tbody tr").filter({ hasText: "2024" }).innerText(), /\$165,000[\s\S]*\$317,700[\s\S]*\$7,810,000/);
  assert.match(await page.locator(".economic-history").filter({ hasText: "Remaining data-center bond principal and interest commitment over time" }).innerText(), /CY2022[\s\S]*\$12,074,400[\s\S]*CY2024[\s\S]*\$11,205,100/);
  assert.equal(await page.locator(".project-research-update").count(), 47);
  const hammondUpdates = (await page.locator(".project-research-update").allInnerTexts()).join("\n");
  assert.match(hammondUpdates, /State debt register shows the existing TIF bond but no separate EID debt/);
  assert.match(hammondUpdates, /Unsubmitted 2025 annual report blocks the debt-series extension/);
  assert.match(hammondUpdates, /2024 data-hall buildout adds dated construction-supply-chain evidence/);
  assert.match(hammondUpdates, /State contract table separates the incentive cap, payment status and job expectations/);
  assert.match(hammondUpdates, /Annual state reports bound when Hammond's incentive balances changed/);
  assert.match(hammondUpdates, /State portal verifies qualified investment and separates the sales-tax exemption/);
  assert.match(hammondUpdates, /Industrial-recovery credit reaches the portal's full certified amount/);
  assert.match(hammondUpdates, /Current EDGE record closes with a small certified amount and no realized-job proof/);
  assert.match(hammondUpdates, /County industry series adds a noncausal employment and payroll benchmark/);
  assert.match(hammondUpdates, /Quarterly local-labor submissions remain a public-evidence gap/);
  await page.getByRole("tab", { name: /Plans & forecasts/ }).click();
  assert.equal(await page.locator(".economic-record").count(), 10);
  const hammondPlans = await page.locator(".economic-record-list").innerText();
  assert.match(hammondPlans, /About \$40,000,000[\s\S]*About \$200,000,000[\s\S]*About \$88,656,629/);
  assert.equal((hammondPlans.match(/Up to \$3,415,000/g) || []).length, 2);
  assert.match(hammondPlans, /About 40 jobs/);
  assert.match(hammondPlans, /\$750,000[\s\S]*45 jobs[\s\S]*\$9,045,773\.82[\s\S]*\$239,530,500/);
  assert.match(await page.locator(".projection-note").innerText(), /Realized spending, jobs and abatements have not been verified/);
  await page.locator(".economic-accounts").screenshot({ path: path.join(out, "hammond-eid-forecasts-mobile.png") });
  await page.getByRole("tab", { name: /Modeled synthesis/ }).click();
  assert.equal(await page.locator(".modeled-record").count(), 2);
  assert.match(await page.locator(".modeled-note").innerText(), /not observed or audited/i);
  const hammondModels = await page.locator(".modeled-record-list").innerText();
  assert.match(hammondModels, /Complete 2024-pay-2025 project-linked local property-tax contribution[\s\S]*\$1,662,655\.9/);
  assert.match(hammondModels, /2024-pay-2025 two-account annual local service-cost break-even threshold[\s\S]*\$1,662,655\.9/);
  const hammondTaxModel = page.locator(".modeled-record").first();
  await hammondTaxModel.locator("summary").click();
  assert.match(await hammondTaxModel.innerText(), /Method:[\s\S]*Formula:[\s\S]*Confidence:[\s\S]*Named parameters[\s\S]*Limitations/);
  await page.locator(".modeled-record-list").screenshot({ path: path.join(out, "hammond-modeled-synthesis-mobile.png") });
  await hammondTaxModel.scrollIntoViewIfNeeded();
  await page.screenshot({ path: path.join(out, "hammond-modeled-synthesis-viewport-mobile.png") });
  const hammondImpact = page.locator(".facility-evidence-summary");
  assert.equal(await hammondImpact.locator(".impact-section").count(), 3);
  assert.match(await hammondImpact.innerText(), /What the collected evidence currently establishes[\s\S]*More than \$50,000,000/);
  assert.match(await hammondImpact.innerText(), /What the current model estimates[\s\S]*\$1,662,655\.9/);
  assert.doesNotMatch(await hammondImpact.innerText(), /Net public fiscal position|Local fiscal margin|Estimated county effects/i);
  assert.equal(await page.locator(".annual-account-coverage, .analysis-readiness").count(), 0);
  await hammondImpact.screenshot({ path: path.join(out, "hammond-impact-account-mobile.png") });
  check("Hammond re-audit adds the omitted personal-property account and retains only bounded fiscal arithmetic");
  await page.getByRole("tab", { name: /Reported activity/ }).click();
  await noOverflow();
  await hammondLocalSpend.screenshot({ path: path.join(out, "hammond-local-contractors-mobile.png") });
  await page.locator(".tax-billing-history").first().screenshot({ path: path.join(out, "hammond-tax-history-mobile.png") });
  await page.locator(".economic-accounts").screenshot({ path: path.join(out, "hammond-depth-evidence-mobile.png") });
  await page.locator(".economic-accounts").screenshot({ path: path.join(out, "hammond-financing-water-mobile.png") });
  await page.locator(".tif-revenue-history").screenshot({ path: path.join(out, "hammond-tif-reconciliation-mobile.png") });
  await page.locator(".tif-debt-history").screenshot({ path: path.join(out, "hammond-tif-debt-mobile.png") });
  await page.locator(".economic-history").filter({ hasText: "Fund investment cost basis" }).screenshot({ path: path.join(out, "hammond-investment-cost-basis-mobile.png") });
  await page.locator(".economic-history").filter({ hasText: "Private equipment line-of-credit balance" }).screenshot({ path: path.join(out, "hammond-private-financing-mobile.png") });
  await page.locator(".economic-history").filter({ hasText: "County data-processing and hosting employment over time" }).screenshot({ path: path.join(out, "hammond-cbp-employment-mobile.png") });
  await page.locator(".economic-record").filter({ hasText: "$28,369,398.27" }).filter({ hasText: "IEDC portal retrieval snapshot" }).screenshot({ path: path.join(out, "hammond-state-incentive-status-mobile.png") });
  await page.locator(".project-research-update").filter({ hasText: "State portal verifies qualified investment and separates the sales-tax exemption" }).screenshot({ path: path.join(out, "hammond-state-data-incentive-mobile.png") });
  await page.locator(".project-research-update").filter({ hasText: "Industrial-recovery credit reaches the portal's full certified amount" }).screenshot({ path: path.join(out, "hammond-irtc-status-mobile.png") });
  await page.locator(".project-research-update").filter({ hasText: "Current EDGE record closes with a small certified amount and no realized-job proof" }).screenshot({ path: path.join(out, "hammond-edge-closeout-mobile.png") });
  await page.locator(".project-research-update").filter({ hasText: "2024 data-hall buildout adds dated construction-supply-chain evidence" }).screenshot({ path: path.join(out, "hammond-supplier-roster-mobile.png") });
  await page.locator(".project-research-update").filter({ hasText: "State contract table separates the incentive cap, payment status and job expectations" }).screenshot({ path: path.join(out, "hammond-state-contract-mobile.png") });
  await page.locator(".project-research-update").filter({ hasText: "Annual state reports bound when Hammond's incentive balances changed" }).screenshot({ path: path.join(out, "hammond-incentive-timeline-mobile.png") });
  await page.locator(".project-research-update").filter({ hasText: "State debt register shows the existing TIF bond but no separate EID debt" }).screenshot({ path: path.join(out, "hammond-eid-debt-screen-mobile.png") });
  await page.locator(".project-research-update").filter({ hasText: "Quarterly local-labor submissions remain a public-evidence gap" }).screenshot({ path: path.join(out, "hammond-local-labor-gap-mobile.png") });
  check("Hammond preserves missing local-labor submissions as a public-evidence gap without solicitation");

  await page.goto(`${url}#/project/prj_study_im3_building_00364289074`);
  await openDetails(".evidence-ledger");
  await page.getByRole("heading", { name: "Microsoft San Antonio", exact: true }).waitFor();
  await page.locator(".account-status").getByText("Research complete · analytical gaps remain", { exact: true }).waitFor();
  await page.locator(".account-count").getByText("19 sourced records · 3 modeled syntheses", { exact: true }).waitFor();
  await openDetails(".evidence-ledger");
  await page.locator(".economic-record").first().waitFor();
  assert.equal(await page.locator(".economic-record").count(), 10);
  assert.match(await page.locator(".economic-record-list").innerText(), /Cumulative[\s\S]*More than \$840,000,000/);
  assert.equal(await page.locator(".history-bar-row").count(), 3);
  await page.getByRole("tab", { name: /Plans & forecasts/ }).click();
  assert.equal(await page.locator(".economic-record").count(), 9);
  assert.match(await page.locator(".economic-record-list").innerText(), /Source-estimated net municipal fiscal impact[\s\S]*\$56,319,724/);
  assert.equal(await page.locator(".fiscal-history").count(), 0);
  await noOverflow();
  check("cumulative investment and the city's modeled net fiscal forecast retain distinct timing and basis");

  await page.goto(`${url}#/project/prj_study_im3_building_00499403180`);
  await openDetails(".evidence-ledger");
  await page.getByRole("heading", { name: "Economic evidence", exact: true }).waitFor();
  assert.match(await page.locator(".record-scope").innerText(), /Supporting infrastructure/);
  await page.locator(".economic-record summary").click();
  assert.match(await page.locator(".economic-record details").innerText(), /financing to Microsoft/);
  assert.equal(await page.locator(".history-bar-row").count(), 0);
  await noOverflow();
  check("water-reuse infrastructure cost preserves payer, system scope and non-annual timing");

  await page.goto(`${url}#/project/prj_study_im3_campus_00231769626`);
  await openDetails(".evidence-ledger");
  await page.getByRole("heading", { name: "Economic evidence", exact: true }).waitFor();
  assert.equal(await page.locator(".tax-billing-history").count(), 2);
  assert.equal(await page.locator(".tax-billing-history tbody tr").count(), 6);
  const googleBill = page.locator(".tax-billing-history").filter({ hasText: "party 155421" });
  const designBill = page.locator(".tax-billing-history").filter({ hasText: "party 130136" });
  assert.match(await googleBill.innerText(), /\$1,119,239,550[\s\S]*\$1,813,378\.61/);
  assert.match(await designBill.innerText(), /\$2,300,544,270[\s\S]*\$3,009,750\.4/);
  assert.match(await designBill.innerText(), /not verified cash collected/);
  assert.doesNotMatch(await page.locator(".tax-billing-history").allTextContents().then(t => t.join(" ")), /FY202|Taxes collected/);
  assert.equal(await page.locator(".economic-record").count(), 23);
  await noOverflow();
  await designBill.screenshot({ path: path.join(out, "tax-billing-mobile.png") });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await designBill.screenshot({ path: path.join(out, "tax-billing-desktop.png") });
  await page.getByRole("tab", { name: /Plans & forecasts/ }).click();
  assert.equal(await page.locator(".economic-record").count(), 4);
  await page.getByRole("tab", { name: /Modeled synthesis/ }).click();
  assert.equal(await page.locator(".modeled-record").count(), 3);
  check("tax bills retain two taxpayer accounts, source tax years and the distinction from cash receipts");

  await page.goto(`${url}#/project/prj_study_im3_campus_00578435601`);
  await openDetails(".evidence-ledger");
  await page.getByRole("heading", { name: "Economic evidence", exact: true }).waitFor();
  const googleTaxBase = page.locator(".economic-history").filter({ hasText: "$53,736,860" }).first();
  await googleTaxBase.getByText("$53,736,860 ↗", { exact: true }).waitFor();
  assert.equal(await googleTaxBase.locator(".history-bar-row").count(), 7);
  assert.match(await googleTaxBase.innerText(), /Calendar years/);
  assert.match(await googleTaxBase.locator(".history-bar-row").nth(5).innerText(), /CY2024[\s\S]*\$53,736,860/);
  const widths = await googleTaxBase.locator(".history-bar-track > div").evaluateAll(nodes => nodes.map(n => parseFloat(n.style.width)));
  assert(widths[5] < widths[4] && widths[6] > widths[5]);
  await page.setViewportSize({ width: 390, height: 844 });
  await noOverflow();
  await googleTaxBase.screenshot({ path: path.join(out, "calendar-tax-base-mobile.png") });
  check("calendar-year assessed values preserve the reported decline and later increase");

  for (const [id, text, count] of [
    ["campus_00009474864", /\$6,800,000/, 1],
  ]) {
    await page.goto(`${url}#/project/prj_study_im3_${id}`);
  await openDetails(".evidence-ledger");
    await page.getByRole("heading", { name: "Economic evidence", exact: true }).waitFor();
    assert.equal(await page.getByRole("tab", { name: /Plans & forecasts/ }).getAttribute("aria-selected"), "true");
    assert.equal(await page.locator(".economic-record").count(), count);
    assert.match(await page.locator(".economic-record-list").innerText(), text);
    await page.getByRole("tab", { name: /Reported activity/ }).click();
    assert.equal(await page.locator(".economic-record").count(), 0);
    await noOverflow();
  }
  await page.goto(`${url}#/project/prj_study_im3_building_00844389014`);
  await openDetails(".evidence-ledger");
  await page.getByRole("heading", { name: "Economic evidence", exact: true }).waitFor();
  assert.equal(await page.locator(".economic-record").count(), 57);
  await page.getByRole("tab", { name: /Plans & forecasts/ }).click();
  assert.equal(await page.locator(".economic-record").count(), 3);
  assert.match(await page.locator(".economic-record-list").innerText(), /70 jobs/);
  check("water contributions and original operating-job commitments remain forecasts");
  await page.goto(`${url}#/project/prj_study_im3_building_00052227492`);
  await openDetails(".evidence-ledger");
  await page.getByRole("heading", { name: "Flexential Minneapolis-Chaska (ViaWest)", exact: true }).waitFor();
  await page.getByRole("heading", { name: "Economic evidence", exact: true }).waitFor();
  await page.locator(".account-count").getByText("26 sourced records · partial coverage", { exact: true }).waitFor();
  assert.equal(await page.locator(".economic-record").count(), 25);
  assert.doesNotMatch(await page.locator(".economic-record-list").innerText(), /IP Stream|West Creek/);
  assert.match(await page.locator(".economic-record-list").innerText(), /\$534,380[\s\S]*\$551,454[\s\S]*\$582,406[\s\S]*\$632,906/);
  const chaskaValues = await page.locator(".economic-history").allInnerTexts().then(rows => rows.join(" "));
  assert.match(chaskaValues, /payable years/);
  assert.equal(await page.locator(".history-bar-row").count(), 16);
  assert.match(chaskaValues, /TY2015[\s\S]*\$11,606,300/);
  assert.match(chaskaValues, /TY2025[\s\S]*\$19,775,100/);
  assert.match(chaskaValues, /TY2027[\s\S]*\$23,544,000/);
  await page.getByRole("tab", { name: /Plans & forecasts/ }).click();
  assert.equal(await page.locator(".economic-record").count(), 1);
  assert.match(await page.locator(".economic-record-list").innerText(), /More than \$60,000,000/);
  await page.getByRole("tab", { name: /Reported activity/ }).click();
  await noOverflow();
  await page.locator(".economic-accounts").screenshot({ path: path.join(out, "chaska-fiscal-mobile.png") });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await noOverflow();
  await page.locator(".economic-accounts").screenshot({ path: path.join(out, "chaska-evidence-desktop.png") });
  check("Flexential Chaska excludes Stream facilities and preserves parcel taxes, permits, capacity, and payable-year values");

  await page.goto(`${url}#/project/prj_study_im3_building_00214321737`);
  await openDetails(".evidence-ledger");
  await page.getByRole("heading", { name: "Markley Lowell", exact: true }).waitFor();
  await page.locator(".account-count").getByText("27 sourced records · 1 modeled synthesis", { exact: true }).waitFor();
  assert.equal(await page.locator(".economic-record").count(), 20);
  assert.equal(await page.locator(".project-research-update").count(), 14);
  assert.match(await page.locator(".economic-record-list").innerText(), /\$25,000[\s\S]*Merrimack Valley Food Bank/);
  await page.getByRole("tab", { name: /Modeled synthesis/ }).click();
  assert.equal(await page.locator(".modeled-record").count(), 1);
  assert.match(await page.locator(".modeled-record-list").innerText(), /break-even[\s\S]*\$534,231\.97/i);
  check("Markley Lowell keeps the recipient contribution and same-account public-cost break-even separate");

  await page.goto(`${url}#/project/prj_study_im3_building_00626785488`);
  await openDetails(".evidence-ledger");
  await page.getByRole("heading", { name: "Meta Los Lunas", exact: true }).waitFor();
  await page.locator(".account-count").getByText("20 sourced records · partial coverage", { exact: true }).waitFor();
  assert.equal(await page.locator(".economic-record").count(), 20);
  assert.equal(await page.locator(".project-research-update").count(), 24);
  assert.match(await page.locator(".economic-record-list").innerText(), /More than 400 jobs[\s\S]*More than \$6,200,000[\s\S]*At least \$5,000/);
  check("Meta Los Lunas preserves campus-level operations and community evidence without inventing a building allocation");

  await page.goto(`${url}#/project/prj_study_im3_building_00172739953`);
  await openDetails(".evidence-ledger");
  await page.getByRole("heading", { name: "Switch Las Vegas NAP7", exact: true }).waitFor();
  await page.locator(".account-count").getByText("16 sourced records · 1 modeled synthesis", { exact: true }).waitFor();
  assert.equal(await page.locator(".economic-record").count(), 16);
  assert.equal(await page.locator(".economic-history").count(), 3);
  assert.equal(await page.locator(".history-bar-row").count(), 6);
  assert.match(await page.locator(".economic-history").allInnerTexts().then(rows => rows.join(" ")), /FY2026[\s\S]*\$87,755,603[\s\S]*FY2027[\s\S]*\$88,942,140/);
  assert.match(await page.locator(".economic-history").allInnerTexts().then(rows => rows.join(" ")), /CY2017[\s\S]*\$200,500,000[\s\S]*CY2018[\s\S]*\$134,200,000/);
  assert.match(await page.locator(".economic-record-list").innerText(), /Quarter ended 2021-03-31[\s\S]*\$23,400,000/);
  assert.match(await page.locator(".economic-record-list").innerText(), /Quarter ended 2021-12-31[\s\S]*\$49,500,000/);
  assert.equal(await page.locator(".project-research-update").count(), 15);
  assert.match(await page.locator(".project-research-update").allInnerTexts().then(rows => rows.join(" ")), /cannot be assigned to this location[\s\S]*resolves the mapped NAP7 building/);
  await page.setViewportSize({ width: 390, height: 844 });
  await noOverflow();
  await page.locator(".economic-accounts").screenshot({ path: path.join(out, "switch-las-vegas-evidence-mobile.png") });
  await page.setViewportSize({ width: 1440, height: 1000 });
  check("NAP7 parcel values and Core Campus capital expenditures retain separate scopes while the combined audit stays contextual");

  await page.goto(`${url}#/project/prj_study_im3_building_00838817907`);
  await openDetails(".evidence-ledger");
  await page.getByRole("heading", { name: "TierPoint Charlotte CL4", exact: true }).waitFor();
  await page.locator(".account-count").getByText("87 sourced records · 3 modeled syntheses", { exact: true }).waitFor();
  assert.equal(await page.locator(".economic-history").count(), 3);
  assert.equal(await page.locator(".tax-billing-history tbody tr").count(), 14);
  assert.match(await page.locator(".tax-billing-history tbody tr").first().innerText(), /2013[\s\S]*\$1,735,800[\s\S]*\$22,294\.61[\s\S]*\$22,294\.61/);
  assert.match(await page.locator(".tax-billing-history tbody tr").last().innerText(), /2026[\s\S]*\$12,003,100[\s\S]*\$94,308\.35[\s\S]*\$94,308\.35/);
  assert.match(await page.locator(".project-research-update").allInnerTexts().then(rows => rows.join(" ")), /building predates the 2014 CL4 opening/);
  await page.setViewportSize({ width: 390, height: 844 });
  await noOverflow();
  await page.locator(".tax-billing-history").screenshot({ path: path.join(out, "tierpoint-cl4-tax-history-mobile.png") });
  await page.setViewportSize({ width: 1440, height: 1000 });
  check("TierPoint CL4 preserves the building owner's parcel assessments, bills and verified payments");

  await page.goto(`${url}#/project/prj_study_im3_building_00388148510`);
  await openDetails(".evidence-ledger");
  await page.getByRole("heading", { name: "TierPoint / Windstream Little Rock", exact: true }).waitFor();
  await page.locator(".account-count").getByText("27 sourced records · 47 modeled syntheses", { exact: true }).waitFor();
  assert.equal(await page.locator(".tax-billing-history tbody tr").count(), 16);
  assert.match(await page.locator(".tax-billing-history tbody tr").filter({ hasText: "2013" }).innerText(), /Not collected[\s\S]*Not collected[\s\S]*Not collected/);
  assert.match(await page.locator(".tax-billing-history tbody tr").filter({ hasText: "2016" }).innerText(), /Not collected[\s\S]*Not collected[\s\S]*Not collected/);
  assert.match(await page.locator(".tax-billing-history tbody tr").filter({ hasText: "2025" }).innerText(), /Not collected[\s\S]*\$82,440\.85[\s\S]*Not collected/);
  assert.match(await page.locator(".tax-billing-history tbody tr").filter({ hasText: "2026" }).innerText(), /\$1,396,547[\s\S]*Not collected[\s\S]*Not collected/);
  assert.match(await page.locator(".economic-record-list").innerText(), /County appraised property value[\s\S]*\$6,982,735/);
  assert.match(await page.locator(".project-research-update").allInnerTexts().then(rows => rows.join(" ")), /building predates the 2012 opening/);
  await page.setViewportSize({ width: 390, height: 844 });
  await noOverflow();
  await page.locator(".tax-billing-history").screenshot({ path: path.join(out, "tierpoint-little-rock-tax-history-mobile.png") });
  await page.setViewportSize({ width: 1440, height: 1000 });
  check("TierPoint Little Rock preserves assessment gaps and the unpaid 2025 parcel charge");

  await page.goto(`${url}#/project/prj_study_im3_point_09190480200`);
  await openDetails(".evidence-ledger");
  await page.getByRole("heading", { name: "Stream Houston I / The Woodlands", exact: true }).waitFor();
  await page.locator(".account-count").getByText("49 sourced records · partial coverage", { exact: true }).waitFor();
  assert.equal(await page.locator(".economic-record").count(), 49);
  assert.equal(await page.locator(".tax-billing-history").count(), 2);
  assert.equal(await page.locator(".tax-billing-history tbody tr").count(), 23);
  assert.equal(await page.locator(".economic-history").count(), 2);
  const streamReal = page.locator(".tax-billing-history").filter({ hasText: "Real-property parcel 9714-07-00103" });
  const streamPersonal = page.locator(".tax-billing-history").filter({ hasText: "business-personal-property account P454338" });
  const streamValues = await page.locator(".economic-history").allInnerTexts().then(rows => rows.join(" "));
  assert.match(streamValues, /TY2014[\s\S]*\$8,500,000[\s\S]*TY2025[\s\S]*\$15,200,000/);
  assert.match(streamValues, /TY2015[\s\S]*\$400,000[\s\S]*TY2025[\s\S]*\$550,000/);
  assert.match(await streamReal.innerText(), /2014[\s\S]*Not collected[\s\S]*\$216,520\.50/);
  assert.match(await streamReal.innerText(), /2025[\s\S]*Not collected[\s\S]*\$290,684\.50/);
  assert.match(await streamPersonal.innerText(), /2015[\s\S]*Not collected[\s\S]*\$9,942\.40/);
  assert.match(await streamPersonal.innerText(), /2025[\s\S]*Not collected[\s\S]*\$9,357\.15/);
  assert.match(await page.locator(".project-research-update").allInnerTexts().then(rows => rows.join(" ")), /remain a separately labeled series/);
  await page.setViewportSize({ width: 390, height: 844 });
  await noOverflow();
  await streamReal.screenshot({ path: path.join(out, "stream-houston-tax-history-mobile.png") });
  await page.locator(".economic-history").first().screenshot({ path: path.join(out, "stream-houston-appraised-history-mobile.png") });
  await page.setViewportSize({ width: 1440, height: 1000 });
  check("Stream Houston preserves separate real-property and equipment values and paid-account histories");

  await page.goto(`${url}#/project/prj_study_im3_building_00377585075`);
  await openDetails(".evidence-ledger");
  await page.getByRole("heading", { name: "EdgeConneX DET01, Southfield", exact: true }).waitFor();
  await page.locator(".account-status").getByText("Research complete · analytical gaps remain", { exact: true }).waitFor();
  await page.locator(".account-count").getByText("53 sourced records · 3 modeled syntheses", { exact: true }).waitFor();
  await openDetails(".evidence-ledger");
  await openDetails(".project-research-ledger");
  assert.equal(await page.locator(".economic-record").count(), 48);
  assert.equal(await page.locator(".tax-billing-history").count(), 3);
  assert.equal(await page.locator(".tax-billing-history tbody tr").count(), 19);
  assert.equal(await page.locator(".economic-history").count(), 2);
  const edgeReal = page.locator(".tax-billing-history").filter({ hasText: "real-property parcel 76-24-33-476-055" });
  const edgeIft = page.locator(".tax-billing-history").filter({ hasText: "Industrial Facilities Tax account 76-IP-13-000-088" });
  const edgePersonal = page.locator(".tax-billing-history").filter({ hasText: "former-IFT commercial-personal account 76-99-43-004-025" });
  assert.match(await edgeReal.innerText(), /2017[\s\S]*\$46,734\.82[\s\S]*\$46,734\.82/);
  assert.match(await edgeReal.innerText(), /2025[\s\S]*Not collected[\s\S]*\$137,034\.94[\s\S]*\$137,034\.94/);
  assert.match(await edgeIft.innerText(), /2016[\s\S]*Not collected[\s\S]*\$24,068\.73[\s\S]*\$24,068\.73/);
  assert.match(await edgePersonal.innerText(), /2020[\s\S]*Not collected[\s\S]*\$110,548\.82[\s\S]*\$110,548\.82/);
  const edgeValues = await page.locator(".economic-history").allInnerTexts().then(rows => rows.join(" "));
  assert.match(edgeValues, /TY2023[\s\S]*\$1,910,905[\s\S]*TY2025[\s\S]*\$2,004,700/);
  assert.match(edgeValues, /TY2023[\s\S]*\$2,107,780[\s\S]*TY2025[\s\S]*\$1,856,400/);
  assert.match(await page.locator(".project-research-update").allInnerTexts().then(rows => rows.join(" ")), /former-IFT personal account begins showing nonzero tax in 2020/);
  await page.getByRole("tab", { name: /Plans & forecasts/ }).click();
  assert.equal(await page.locator(".economic-record").count(), 5);
  assert.match(await page.locator(".economic-record-list").innerText(), /\$16,251,600[\s\S]*\$18,935,500[\s\S]*27 jobs[\s\S]*\$67,000/);
  assert.match(await page.locator(".projection-note").innerText(), /Realized spending, jobs and abatements have not been verified/);
  await page.setViewportSize({ width: 390, height: 844 });
  await noOverflow();
  await page.locator(".economic-accounts").screenshot({ path: path.join(out, "edgeconnex-det01-forecasts-mobile.png") });
  await page.getByRole("tab", { name: /Reported activity/ }).click();
  await edgeReal.screenshot({ path: path.join(out, "edgeconnex-det01-tax-history-mobile.png") });
  await page.setViewportSize({ width: 1440, height: 1000 });
  check("EdgeConneX DET01 keeps real, IFT and former-IFT accounts separate from investment, job and wage forecasts");

  await page.goto(`${url}#/project/prj_study_im3_point_06685432442`);
  await openDetails(".evidence-ledger");
  await page.getByRole("heading", { name: "Switch Citadel / Tahoe Reno 1", exact: true }).waitFor();
  await page.locator(".account-count").getByText("86 sourced records · 4 modeled syntheses", { exact: true }).waitFor();
  await page.locator(".account-status").getByText("Research complete · analytical gaps remain", { exact: true }).waitFor();
  await openDetails(".project-research-ledger");
  assert.equal(await page.locator(".economic-record").count(), 78);
  const storeyTaxHistories = page.locator(".tax-billing-history");
  const storeyRealTaxHistory = storeyTaxHistories.filter({ hasText: "NV RNO 1, LLC real-property parcel 005-012-23" });
  assert.equal(await storeyTaxHistories.locator("tbody tr").count(), 15);
  assert.match(await storeyTaxHistories.locator("tbody tr").filter({ hasText: "2019" }).innerText(), /\$10,956,667\.05[\s\S]*\$0[\s\S]*Not collected/);
  assert.match(await storeyTaxHistories.locator("tbody tr").filter({ hasText: "$125,198,623.90" }).innerText(), /\$125,198,623\.90[\s\S]*\$1,083,187\.19[\s\S]*\$1,083,187\.19/);
  assert.match(await storeyRealTaxHistory.innerText(), /\$2,239,229\.35[\s\S]*\$2,369,299\.77[\s\S]*\$2,381,598\.47/);
  assert.equal(await page.locator(".economic-history").count(), 3);
  assert.equal(await page.locator(".history-bar-row").count(), 27);
  assert.equal(await page.locator(".project-research-update").count(), 22);
  assert.match(await page.locator(".project-research-update").allInnerTexts().then(rows => rows.join(" ")), /resolves Switch personal property at the Citadel campus/);
  assert.match(await page.locator(".economic-record-list").innerText(), /\$356,000[\s\S]*More than \$2,000,000/);
  const storeyDonation = page.locator(".economic-record").filter({ hasText: "$356,000" });
  await page.getByRole("tab", { name: /Plans & forecasts/ }).click();
  assert.equal(await page.locator(".economic-record").count(), 8);
  assert.match(await page.locator(".economic-record-list").innerText(), /About \$1,000,000,000[\s\S]*\$1,386,677,024[\s\S]*\$100,000/);
  await page.getByRole("tab", { name: /Reported activity/ }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await noOverflow();
  await storeyDonation.screenshot({ path: path.join(out, "switch-storey-community-contribution-mobile.png") });
  await storeyTaxHistories.first().screenshot({ path: path.join(out, "switch-citadel-tax-history-mobile.png") });
  await storeyRealTaxHistory.screenshot({ path: path.join(out, "switch-citadel-real-property-tax-mobile.png") });
  await page.getByRole("tab", { name: /Modeled synthesis/ }).click();
  assert.equal(await page.locator(".modeled-record").count(), 4);
  const storeyModels = await page.locator(".modeled-record-list").innerText();
  assert.match(storeyModels, /Modeled combined real and personal property tax paid[\s\S]*\$3,380,719\.65[\s\S]*\$3,452,486\.96/);
  assert.match(storeyModels, /Modeled cumulative verified property tax paid[\s\S]*\$11,324,644\.79/);
  assert.match(storeyModels, /Annual local service-cost break-even threshold[\s\S]*\$3,452,486\.96 \/ year/);
  await page.locator(".modeled-record").first().locator("summary").click();
  assert.match(await page.locator(".modeled-record").first().innerText(), /Formula:[\s\S]*Named parameters[\s\S]*Limitations/);
  await page.locator(".modeled-record-list").screenshot({ path: path.join(out, "switch-storey-modeled-synthesis-mobile.png") });
  const storeyImpact = page.locator(".facility-evidence-summary");
  assert.equal(await storeyImpact.locator(".impact-section").count(), 3);
  assert.match(await storeyImpact.innerText(), /What the collected evidence currently establishes[\s\S]*\$452,372,959/);
  assert.match(await storeyImpact.innerText(), /What the current model estimates[\s\S]*\$3,452,486\.96/);
  assert.doesNotMatch(await storeyImpact.innerText(), /Net public fiscal position|Local fiscal margin|Estimated county effects/i);
  assert.equal(await page.locator(".annual-account-coverage, .analysis-readiness").count(), 0);
  await storeyImpact.screenshot({ path: path.join(out, "switch-storey-impact-account-mobile.png") });
  await page.setViewportSize({ width: 1440, height: 1000 });
  check("Citadel re-audit keeps direct records separate and retains only bounded fiscal arithmetic");
  await page.goto(`${url}#/project/prj_study_im3_building_01073720208`);
  await openDetails(".evidence-ledger");
  await page.getByRole("heading", { name: "Google Council Bluffs", exact: true }).waitFor();
  await page.locator(".economic-record").first().waitFor();
  await page.locator(".account-count").getByText("31 sourced records · 8 modeled syntheses", { exact: true }).waitFor();
  assert.equal(await page.locator(".economic-record").count(), 27);
  assert.equal(await page.locator(".economic-history").count(), 1);
  assert.equal(await page.locator(".economic-history .history-bar-row").count(), 2);
  assert.match(await page.locator(".economic-record-list").innerText(), /About \$96,600,000[\s\S]*\$1,700,000,000[\s\S]*70 employees[\s\S]*\$285,000[\s\S]*\$92,462,323[\s\S]*\$9,060,288/);
  assert.match(await page.locator(".economic-record-list").innerText(), /Gable Corp[\s\S]*Questa LLC[\s\S]*Tetra LLC/);
  await page.getByRole("tab", { name: /Plans & forecasts/ }).click();
  assert.equal(await page.locator(".economic-record").count(), 4);
  assert.match(await page.locator(".economic-record-list").innerText(), /\$600,000,000[\s\S]*31 jobs[\s\S]*\$36,600,000/);
  assert.match(await page.locator(".projection-note").innerText(), /Realized spending, jobs and abatements have not been verified/);
  await page.setViewportSize({ width: 390, height: 844 });
  await noOverflow();
  await page.locator(".economic-accounts").screenshot({ path: path.join(out, "council-bluffs-evidence-mobile.png") });
  await page.getByRole("tab", { name: /Modeled synthesis/ }).click();
  assert.equal(await page.locator(".modeled-record").count(), 8);
  assert.match(await page.locator(".modeled-record-list").innerText(), /Permit-anchored total construction job-year benchmark equivalent[\s\S]*888\.23 job-years[\s\S]*Unallocated Council Bluffs location water-consumption identity[\s\S]*1,010,200,000 gallons \/ year/);
  check("Council Bluffs completed award, taxpayer stocks, forecasts and modeled synthesis remain separate");
  await page.goto(`${url}#/project/prj_study_im3_building_00472761713`);
  await openDetails(".evidence-ledger");
  await page.getByRole("heading", { name: "Economic evidence", exact: true }).waitFor();
  assert.equal(await page.locator(".economic-record").count(), 18);
  assert.equal(await page.locator(".tax-billing-history tbody tr").count(), 15);
  assert.match(await page.locator(".tax-billing-history tbody tr").first().innerText(), /2011[\s\S]*\$100,000,000[\s\S]*Not collected/);
  assert.match(await page.locator(".tax-billing-history tbody tr").last().innerText(), /2025[\s\S]*\$102,000,000[\s\S]*\$2,169,540[\s\S]*\$2,169,540/);
  await page.locator(".economic-accounts .research-details summary").click();
  assert.match(await page.locator(".economic-accounts .research-details").innerText(), /Structured data and published layout checked/);
  assert.match(await page.locator(".project-research-update").allInnerTexts().then(rows => rows.join(" ")), /Township record links NYSE to the assessed parcel/);
  await page.setViewportSize({ width: 390, height: 844 });
  await noOverflow();
  await page.locator(".tax-billing-history").screenshot({ path: path.join(out, "nyse-mahwah-tax-history-mobile.png") });
  check("NYSE parcel assessments, billed charges and verified 2024-2025 payments remain distinct");
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto(`${url}#/project/prj_study_im3_building_00598261190`);
  await openDetails(".evidence-ledger");
  await page.getByRole("heading", { name: "State Farm Olathe", exact: true }).waitFor();
  await page.locator(".account-count").getByText("32 sourced records · 4 modeled syntheses", { exact: true }).waitFor();
  assert.equal(await page.locator(".economic-record").count(), 32);
  assert.equal(await page.locator(".tax-billing-history tbody tr").count(), 7);
  assert.equal(await page.locator(".tax-billing-history thead th").count(), 4);
  assert.match(await page.locator(".tax-billing-history tbody tr").last().innerText(), /2025[\s\S]*\$19,994,965[\s\S]*\$2,298,781\.14[\s\S]*\$2,298,781\.14/);
  assert.equal(await page.locator(".economic-history .history-bar-row").count(), 5);
  assert.match(await page.locator(".economic-history").innerText(), /TY2024[\s\S]*\$91,415,000/);
  assert.match(await page.locator(".economic-record-list").innerText(), /Estimated cumulative capital expenditure[\s\S]*About \$169,778,850/);
  assert.match((await page.locator(".project-research-update").allInnerTexts()).join("\n"), /County parcel links HMC ownership and the State Farm data center/);
  await page.setViewportSize({ width: 390, height: 844 });
  await noOverflow();
  await page.locator(".tax-billing-history").screenshot({ path: path.join(out, "state-farm-olathe-tax-history-mobile.png") });
  check("State Farm parcel values, bills, paid account totals and estimated cumulative capex stay distinct");
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto(`${url}#/project/prj_study_im3_building_00300974499`);
  await page.getByRole("heading", { name: "About this project", exact: true }).waitFor();
  assert.match(await page.locator(".project-description").innerText(), /converted and expanded data-center facility[\s\S]*began serving customers in March 2017/i);
  assert(await page.locator(".project-description").evaluate(element =>
    Boolean(element.compareDocumentPosition(document.querySelector(".project-overview")) & Node.DOCUMENT_POSITION_FOLLOWING)
  ), "project description must appear before the study-rationale card");
  await page.locator(".project-description").screenshot({ path: path.join(out, "apple-mesa-project-description-desktop.png") });
  await page.setViewportSize({ width: 390, height: 844 });
  await noOverflow();
  await page.locator(".project-description").screenshot({ path: path.join(out, "apple-mesa-project-description-mobile.png") });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await openDetails(".evidence-ledger");
  await page.getByRole("heading", { name: "Economic evidence", exact: true }).waitFor();
  await page.locator(".account-count").getByText("105 sourced records · 3 modeled syntheses", { exact: true }).waitFor();
  await page.locator(".account-status").getByText("Research complete · analytical gaps remain", { exact: true }).waitFor();
  await openDetails(".project-research-ledger");
  assert.equal(await page.locator(".economic-record").count(), 101);
  assert.equal(await page.locator(".tax-billing-history").count(), 2);
  assert.equal(await page.locator(".tax-billing-history tbody tr").count(), 22);
  const appleEquipment = page.locator(".tax-billing-history").filter({ hasText: "Apple Inc. business personal property" });
  const appleReal = page.locator(".tax-billing-history").filter({ hasText: "Platypus Development LLC" });
  assert.match(await appleEquipment.innerText(), /2025[\s\S]*\$8,289,401[\s\S]*\$966,899\.82[\s\S]*\$966,899\.82/);
  assert.match(await appleEquipment.innerText(), /2026[\s\S]*\$15,036,685[\s\S]*Not collected[\s\S]*Not collected/);
  assert.match(await appleReal.innerText(), /2025[\s\S]*\$10,109,024[\s\S]*\$906,476\.10[\s\S]*\$906,476\.10/);
  assert.equal(await page.locator(".economic-history").count(), 3);
  const appleElectricity = page.locator(".economic-history").filter({ hasText: "Reported annual electricity use" });
  assert.equal(await appleElectricity.locator(".history-bar-row").count(), 9);
  assert.match(await appleElectricity.innerText(), /FY2017[\s\S]*45,000,000 kWh \/ year[\s\S]*FY2025[\s\S]*563,000,000 kWh \/ year/);
  assert.match(await page.locator(".economic-record-list").innerText(), /50 MW[\s\S]*4\.67 MW[\s\S]*\$32,991,875\.28[\s\S]*About \$2,000,000,000/);
  const appleUpdates = (await page.locator(".project-research-update").allInnerTexts()).join("\n");
  assert.match(appleUpdates, /Nine-year electricity series/);
  assert.match(appleUpdates, /separate Apple equipment from Apple-associated real estate/);
  assert.match(appleUpdates, /Mesa permit dataset reconciled exhaustively at the address/);
  await page.setViewportSize({ width: 390, height: 844 });
  await noOverflow();
  await appleEquipment.screenshot({ path: path.join(out, "apple-mesa-tax-history-mobile.png") });
  await appleElectricity.screenshot({ path: path.join(out, "apple-mesa-electricity-history-mobile.png") });
  await page.getByRole("tab", { name: /Plans & forecasts/ }).click();
  assert.equal(await page.locator(".economic-record").count(), 4);
  assert.match(await page.locator(".economic-record-list").innerText(), /\$2,000,000,000[\s\S]*150 jobs[\s\S]*Up to 500 jobs[\s\S]*\$25,000,000/);
  await page.locator(".economic-record-list").screenshot({ path: path.join(out, "apple-mesa-forecasts-mobile.png") });
  await page.getByRole("tab", { name: /Modeled synthesis/ }).click();
  assert.equal(await page.locator(".modeled-record").count(), 3);
  assert.match(await page.locator(".modeled-note").innerText(), /not observed or audited/i);
  const appleModels = await page.locator(".modeled-record-list").innerText();
  assert.match(appleModels, /Modeled BPP FTZ assessment-ratio tax reduction versus Class 1[\s\S]*\$3,250,864\.51[\s\S]*\$2,421,356\.69[\s\S]*\$2,127,179\.6/);
  await page.locator(".modeled-record").first().locator("summary").click();
  assert.match(await page.locator(".modeled-record").first().innerText(), /Method:[\s\S]*Formula:[\s\S]*Confidence:[\s\S]*Named parameters[\s\S]*Limitations/);
  await page.locator(".modeled-record-list").screenshot({ path: path.join(out, "apple-mesa-modeled-synthesis-mobile.png") });
  const appleImpact = page.locator(".facility-evidence-summary");
  assert.equal(await appleImpact.locator(".impact-section").count(), 3);
  assert.match(await appleImpact.innerText(), /What the collected evidence currently establishes[\s\S]*About \$2,000,000,000/);
  assert.match(await appleImpact.innerText(), /What the current model estimates[\s\S]*\$2,127,179\.6/);
  assert.doesNotMatch(await appleImpact.innerText(), /Net public fiscal position|Local fiscal margin|Local service-cost allocation|Estimated county effects/i);
  assert.equal(await page.locator(".annual-account-coverage, .analysis-readiness").count(), 0);
  await appleImpact.screenshot({ path: path.join(out, "apple-mesa-impact-account-mobile.png") });
  check("Apple Mesa re-audit adds exhaustive permit evidence and retains only bounded FTZ counterfactuals");
  check("Apple Mesa source records, forecasts and three last-resort modeled syntheses remain distinct");
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto(`${url}#/project/prj_study_im3_building_00664938835`);
  await openDetails(".evidence-ledger");
  await page.getByRole("heading", { name: "Expedient Milwaukee / Franklin", exact: true }).waitFor();
  await page.locator(".account-count").getByText("16 sourced records · 7 modeled syntheses", { exact: true }).waitFor();
  assert.equal(await page.locator(".economic-record").count(), 15);
  assert.equal(await page.locator(".tax-billing-history tbody tr").count(), 8);
  assert.match(await page.locator(".tax-billing-history tbody tr").first().innerText(), /2024[\s\S]*\$3,856,900/);
  assert.match(await page.locator(".economic-record-list").innerText(), /\$3,856,900[\s\S]*\$580,190[\s\S]*\$250,132[\s\S]*\$60,347\.17/);
  await page.setViewportSize({ width: 390, height: 844 });
  await noOverflow();
  await page.locator(".economic-accounts").screenshot({ path: path.join(out, "expedient-franklin-actuals-mobile.png") });
  await page.getByRole("tab", { name: /Plans & forecasts/ }).click();
  assert.equal(await page.locator(".economic-record").count(), 1);
  assert.match(await page.locator(".economic-record-list").innerText(), /12 jobs/);
  await page.locator(".economic-accounts").screenshot({ path: path.join(out, "expedient-franklin-evidence-mobile.png") });
  await page.getByRole("tab", { name: /Modeled synthesis/ }).click();
  assert.equal(await page.locator(".modeled-record").count(), 7);
  const expedientModels = await page.locator(".modeled-record-list").innerText();
  assert.match(expedientModels, /Annual local public-service-cost break-even threshold[\s\S]*\$60,347\.17 \/ year/);
  assert.doesNotMatch(expedientModels, /Net public fiscal position|Local fiscal margin/);
  check("Expedient adaptive reuse keeps parcel stocks, forecasts, fiscal threshold and modeled channels separate");
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto(`${url}#/project/prj_study_im3_building_00888253616`);
  await openDetails(".evidence-ledger");
  await page.getByRole("heading", { name: "NTT Silicon Valley SV1", exact: true }).waitFor();
  await page.locator(".account-count").getByText("17 sourced records · 4 modeled syntheses", { exact: true }).waitFor();
  assert.equal(await page.locator(".economic-record").count(), 15);
  assert.match(await page.locator(".economic-record-list").innerText(), /\$159,579,996[\s\S]*\$83,066,779/);
  assert.match(await page.locator(".economic-record-list").innerText(), /\$125,405,765/);
  assert.match(await page.locator(".economic-record-list").innerText(), /\$1,024,370\.76/);
  assert.match((await page.locator(".project-research-update").allInnerTexts()).join("\n"), /1150 Walsh Avenue[\s\S]*1160 Walsh Avenue/);
  await page.getByRole("tab", { name: /Plans & forecasts/ }).click();
  assert.equal(await page.locator(".economic-record").count(), 2);
  assert.match(await page.locator(".economic-record-list").innerText(), /Up to 40 jobs[\s\S]*173,752 gallons \/ year/);
  await page.getByRole("tab", { name: /Modeled synthesis/ }).click();
  assert.equal(await page.locator(".modeled-record").count(), 4);
  await page.setViewportSize({ width: 390, height: 844 });
  await noOverflow();
  await page.locator(".economic-accounts").screenshot({ path: path.join(out, "ntt-sv1-evidence-mobile.png") });
  check("NTT SV1 keeps assessment-appeal positions, job plans and water design estimates distinct");
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto(`${url}#/project/prj_study_im3_building_00903236619`);
  await openDetails(".evidence-ledger");
  await page.getByRole("heading", { name: "Quicken Loans Technology Center, Corktown", exact: true }).waitFor();
  await page.locator(".account-count").getByText("8 sourced records · 2 modeled syntheses", { exact: true }).waitFor();
  assert.equal(await page.locator(".economic-record").count(), 7);
  assert.equal(await page.locator(".economic-history").count(), 2);
  assert.match(await page.locator(".economic-history").nth(0).innerText(), /CY2025[\s\S]*\$3,298,400[\s\S]*CY2026[\s\S]*\$3,643,800/);
  assert.match(await page.locator(".economic-history").nth(1).innerText(), /CY2025[\s\S]*\$2,679,332[\s\S]*CY2026[\s\S]*\$2,813,298/);
  assert.match((await page.locator(".project-research-update").allInnerTexts()).join("\n"), /whole-parcel stocks[\s\S]*partial-building tenancy[\s\S]*zero-water cooling claim remains unmetered/i);
  await page.getByRole("tab", { name: /Plans & forecasts/ }).click();
  assert.equal(await page.locator(".economic-record").count(), 1);
  assert.match(await page.locator(".economic-record-list").innerText(), /\$24,044\.58/);
  await page.getByRole("tab", { name: /Modeled synthesis/ }).click();
  assert.equal(await page.locator(".modeled-record").count(), 2);
  assert.match(await page.locator(".modeled-record-list").innerText(), /Whole-facility annual electricity-throughput sensitivity[\s\S]*Electrician-only construction wage-payroll sensitivity/);
  await page.getByRole("tab", { name: /Reported activity/ }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await noOverflow();
  await page.locator(".economic-accounts").screenshot({ path: path.join(out, "quicken-corktown-evidence-mobile.png") });
  check("Quicken Corktown keeps whole-parcel values separate from partial-building tenancy and water claims");

  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto(`${url}#/county/18089`);
  await page.getByRole("heading", { name: "Facility contribution to Lake County", exact: true }).waitFor();
  const countyImpact = page.locator(".county-impact-account");
  await countyImpact.waitFor();
  assert.equal(await countyImpact.locator(".impact-section").count(), 2);
  assert.match(await countyImpact.innerText(), /What public records establish[\s\S]*Recurring local tax contribution and break-even/);
  assert.doesNotMatch(await countyImpact.innerText(), /Construction-period contribution|County outcome comparison/);
  await page.getByRole("heading", { name: "How the host economy changed", exact: true }).waitFor();
  assert.equal(await page.locator(".county-trend").count(), 4);
  assert.equal(await page.locator(".county-trend-point").count(), 96);
  assert.equal(await page.locator('.county-trend-point[data-year="2012"]').count(), 4);
  assert.equal(await page.locator(".county-trend-point.endpoint").count(), 8);
  assert.equal(await page.locator(".county-trend-years span").count(), 24);
  assert.equal(await page.locator(".county-history-table tbody tr").count(), 24);
  await page.getByRole("heading", { name: "Comparable counties without known data-center records", exact: true }).waitFor();
  assert.equal(await page.locator(".county-comparison-list article").count(), 5);
  assert.match(await page.locator(".county-comparison-section").innerText(), /three national data-center screens[\s\S]*seven-domain review status is retained/i);
  assert.doesNotMatch(await page.locator(".county-profile-page").innerText(), /IM3 source records|Analysis readiness|Annual-account coverage/);
  await page.locator(".county-study-account").screenshot({ path: path.join(out, "lake-county-impact-account-desktop.png") });
  await page.setViewportSize({ width: 390, height: 844 });
  await noOverflow();
  await page.locator(".county-history-section").screenshot({ path: path.join(out, "lake-county-history-mobile.png") });
  check("completed county page presents annual markers across observed 2001–2024 county trends");

  const timelineDataset = await page.evaluate(async () => (await fetch("/data/v1/study/project-media-timelines.json")).json());
  assert.equal(timelineDataset.timelines.length, 36);
  assert.equal(timelineDataset.timelines.every(timeline => timeline.events.length >= 2), true);
  const representativeTimelines = [
    ["prj_study_im3_building_00300974499", "Apple Mesa", 12],
    ["prj_study_im3_point_06685432442", "Switch Citadel / Tahoe Reno 1", 11],
    ["prj_study_im3_building_00978934687", "Digital Crossroad DX-1, Hammond", 11],
  ];
  for (const [projectId, projectName, eventCount] of representativeTimelines) {
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.goto(`${url}#/project/${projectId}`);
    await page.getByRole("heading", { name: projectName, exact: true }).waitFor();
    await page.locator(".media-timeline").waitFor({ state: "attached" });
    await openDetails(".project-research-ledger");
    assert.equal(await page.locator(".media-timeline > li").count(), eventCount);
    assert.equal(await page.locator(".media-timeline .timeline-sources a").count() >= eventCount, true);
    const timelineLinks = await page.locator(".media-timeline .timeline-sources a").evaluateAll(links => links.map(link => link.href));
    const ledgerLinks = await page.locator(".source-ledger .source-list a").evaluateAll(links => links.map(link => link.href));
    assert.equal(timelineLinks.every(link => ledgerLinks.includes(link)), true);
  }
  assert.match(await page.locator(".media-timeline").innerText(), /ground[\s\S]*completed[\s\S]*expansion[\s\S]*public questions[\s\S]*expires/i);
  check("all project pages have timeline data and representative pages render sourced activity events");

  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(`${url}#/study`);
  await page.getByLabel("Search projects").waitFor();
  await noOverflow();
  await page.screenshot({ path: path.join(out, "register-mobile.png") });
  check("project and register at mobile width");

  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto(`${url}#/rejected`);
  await page.getByRole("heading", { name: "Rejected & withdrawn proposals", exact: true }).waitFor();
  assert.equal(await page.locator(".rejected-project-card").count(), 7);
  assert.match(await page.locator(".rejected-counts").innerText(), /7[\s\S]*verified proposals[\s\S]*68[\s\S]*cited sources[\s\S]*49[\s\S]*sourced events/i);
  await page.getByRole("link", { name: "Etheridge Lakes Data Center", exact: true }).click();
  await page.getByRole("heading", { name: "Proposal, opposition, decision, and aftermath", exact: true }).waitFor();
  assert.equal(await page.locator(".rejected-timeline > li").count(), 8);
  assert.match(await page.locator(".proposal-scale-grid:not(.county-outcome-grid)").innerText(), /350,000 square feet[\s\S]*22.6 acres/i);
  assert.match(await page.locator(".site-afterlife").innerText(), /Interpretation boundary/i);
  await page.setViewportSize({ width: 390, height: 844 });
  await noOverflow();
  await page.screenshot({ path: path.join(out, "rejected-project-mobile.png") });
  check("rejected proposal register and sourced case profile render without overflow");

  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto(`${url}#/controls`);
  await page.getByRole("heading", { name: /Comparable communities/ }).waitFor();
  assert.match(await page.locator(".comparison-summary").innerText(), /35[\s\S]*420[\s\S]*235[\s\S]*2,338/);
  assert.match(await page.locator(".comparison-caveat").innerText(), /175 counties surfaced by candidate-specific research were removed/i);
  assert.equal(await page.locator(".comparison-candidate").count(), 5);
  assert.equal(await page.locator(".comparison-candidate-title em").allTextContents().then(values => values.every(value => /Absence review required|Seven-domain review cleared/i.test(value))), true);
  await page.locator(".comparison-host-select select").selectOption("04013");
  await page.getByRole("heading", { name: "Maricopa County, AZ" }).waitFor();
  assert.equal(await page.locator(".comparison-candidate").count(), 5);
  assert.match(await page.locator(".control-counts").innerText(), /3,144[\s\S]*231[\s\S]*2,913[\s\S]*0/);
  assert.match(await page.locator(".control-warning").innerText(), /does not mean “never considered/i);
  await page.locator(".control-filters select").selectOption("VA");
  await page.getByRole("heading", { name: "Fauquier County, VA" }).waitFor();
  assert.equal(await page.locator(".control-card").count(), 133);
  assert.match(await page.getByRole("heading", { name: "Fauquier County, VA" }).locator("xpath=..").innerText(), /Facility \+ stopped proposal/i);
  await page.setViewportSize({ width: 390, height: 844 });
  await noOverflow();
  await page.screenshot({ path: path.join(out, "comparison-counties-mobile.png") });
  check("comparison-county screen preserves unresolved absence and state-partitioned records");

  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.evaluate(() => performance.clearResourceTimings());
  await page.goto(`${url}#/map`);
  await page.locator("canvas").waitFor();
  await page.waitForFunction(() => !document.querySelector(".map-message") && !document.querySelector(".map-loading"), undefined, { timeout: 45000 });
  assert.deepEqual(await page.evaluate(() => ({
    sidebar: getComputedStyle(document.querySelector(".sidebar")).backgroundColor,
    map: getComputedStyle(document.querySelector(".map-section")).backgroundColor,
  })), { sidebar: "rgb(11, 14, 20)", map: "rgb(16, 23, 27)" });
  assert.match(await page.locator(".review-key").innerText(), /operating project audit \(30\)[\s\S]*rejected \/ withdrawn \(7\)/i);
  assert.doesNotMatch(await page.locator(".legend").innerText(), /IM3|pending|merged|queued/i);
  await page.getByLabel("Research-complete project markers").selectOption("Colocation");
  assert.match(await page.locator(".review-key").innerText(), /operating project audit \(12\)/i);
  await page.getByLabel("Research-complete project markers").selectOption("");
  await page.screenshot({ path: path.join(out, "map-desktop.png") });
  assert.doesNotMatch(await page.locator(".sidebar").innerText(), /Source records|Building records|Campus records|Observed footprint|First-entry research/i);
  const mapResources = await page.evaluate(() => performance.getEntriesByType("resource").map(entry => entry.name));
  assert.equal(mapResources.some(name => name.endsWith("/data/v1/maps/facilities.geojson")), false);
  assert.equal(mapResources.some(name => name.includes("/data/v1/counties/")), false);
  assert.equal(mapResources.some(name => name.includes("/data/v1/panels/county-economic-history/")), false);
  const response = await page.request.get(`${url}data/v1/study/index.json`);
  const study = await response.json();
  assert.equal(study.projects.length, 36);
  assert.equal(study.projects.filter(p => p.research_completion_status === "account_research_complete").length, 30);
  assert.equal(study.projects.filter(p => p.model_completeness.status === "full_modeled_account").length, 0);
  const descriptionPage = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  for (const completed of study.projects.filter(project => project.research_completion_status === "account_research_complete")) {
    await descriptionPage.goto(`${url}#/project/${completed.project_id}`);
    await descriptionPage.getByRole("heading", { name: completed.name, exact: true }).waitFor();
    await descriptionPage.locator(".project-description").waitFor();
    assert.equal(await descriptionPage.locator(".project-description").count(), 1, `${completed.name} must render one project description`);
    await descriptionPage.getByRole("heading", { name: "About this project", exact: true }).waitFor();
    await descriptionPage.getByRole("heading", { name: "Why this project is in the study", exact: true }).waitFor();
    assert(await descriptionPage.locator(".project-description").evaluate(element =>
      Boolean(element.compareDocumentPosition(document.querySelector(".project-overview")) & Node.DOCUMENT_POSITION_FOLLOWING)
    ), `${completed.name} must render the project description before the study rationale`);
  }
  await descriptionPage.close();
  check("all thirty completed project pages render one description above the study rationale");
  const target = study.projects.find(p => p.name === "Apple Mesa");
  const canvas = await page.locator("canvas").boundingBox();
  const world = 512 * 2 ** 3.25;
  const mercatorY = lat => (1 - Math.asinh(Math.tan(lat * Math.PI / 180)) / Math.PI) / 2;
  const screenPoint = project => ({
    x: canvas.x + canvas.width / 2 + (project.longitude + 98.5) / 360 * world,
    y: canvas.y + canvas.height / 2 + (mercatorY(project.latitude) - mercatorY(38.5)) * world,
  });
  const { x: targetX, y: targetY } = screenPoint(target);
  const mapPopup = page.locator(".study-map-popup .maplibregl-popup-content");
  const washApple = screenPoint(study.projects.find(p => p.name === "Apple Washoe County campus"));
  const storeySwitch = screenPoint(study.projects.find(p => p.name === "Switch Citadel / Tahoe Reno 1"));
  await page.mouse.move(washApple.x - 12, washApple.y);
  await mapPopup.waitFor();
  assert.match(await mapPopup.innerText(), /Apple Washoe County campus/);
  await page.mouse.move(storeySwitch.x + 12, storeySwitch.y);
  await mapPopup.waitFor();
  assert.match(await mapPopup.innerText(), /Switch Citadel \/ Tahoe Reno 1/);
  check("nearby Washoe and Storey projects render as two separately reachable markers");
  await page.mouse.move(targetX - 40, targetY);
  await page.mouse.move(targetX - 20, targetY);
  const countyPopupLink = page.locator(".study-map-popup a");
  await countyPopupLink.waitFor();
  assert.equal(await countyPopupLink.getAttribute("href"), `#/county/${target.county_fips}`);
  check("completed county popup restores a direct link to the county detail page");
  await page.mouse.move(targetX, targetY);
  await mapPopup.waitFor();
  assert.deepEqual(await mapPopup.evaluate(element => ({
    background: getComputedStyle(element).backgroundColor,
    color: getComputedStyle(element).color,
    title: getComputedStyle(element.querySelector("strong")).color,
  })), { background: "rgb(12, 16, 22)", color: "rgb(220, 232, 238)", title: "rgb(255, 255, 255)" });
  await page.screenshot({ path: path.join(out, "map-popup-desktop.png") });
  await page.mouse.click(targetX, targetY);
  await page.waitForURL(`**/project/${target.project_id}`);
  await page.getByRole("heading", { name: "Sources & research history" }).waitFor();
  check("map preserves all thirty completed project audits while keeping analytical completeness separate");

  const legacyPage = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  await legacyPage.route("**/data/v1/study/index.json?*", async route => {
    const legacyStudy = structuredClone(study);
    for (const project of legacyStudy.projects) delete project.research_completion_status;
    await route.fulfill({ json: legacyStudy });
  });
  await legacyPage.goto(`${url}#/map`, { waitUntil: "domcontentloaded" });
  await legacyPage.getByText("25 completed project accounts and 7 rejected or withdrawn proposals are mapped.", { exact: false }).waitFor();
  assert.match(await legacyPage.locator(".review-key").innerText(), /operating project audit \(25\)/i);
  await legacyPage.close();
  check("map remains populated when a browser holds an index without the research-completion field");

  for (const candidate of study.projects.filter(project => project.model_completeness.status === "incomplete")) {
    await page.goto(`${url}#/project/${candidate.project_id}`);
    await page.getByRole("heading", { name: candidate.name, exact: true }).waitFor();
    const summary = page.locator(".facility-evidence-summary");
    await summary.waitFor();
    assert((await summary.locator(".facility-evidence-table tbody tr").count()) > 0, `${candidate.name} has no visible evidence rows`);
    assert.equal(await page.locator(".error-panel").count(), 0, `${candidate.name} rendered an error`);
    assert.equal(await page.locator(".evidence-ledger").getAttribute("open"), null, `${candidate.name} audit ledger should be collapsed`);
  }
  check("all incomplete facility routes render visible evidence summaries with collapsed audit ledgers");

  await page.goto(`${url}#/project/prj_study_missing`);
  await page.getByRole("heading", { name: "Project or page not found" }).waitFor();
  await page.getByRole("link", { name: "Evidence & methodology", exact: true }).click();
  await page.getByRole("heading", { name: "County first entry remains a specific question" }).waitFor();
  check("unknown project and methodology navigation");

  assert.deepEqual(errors, [], "browser runtime errors");
  await writeFile(path.join(out, "browser-checks.json"), JSON.stringify({ url, checks, runtime_errors: errors }, null, 2) + "\n");
} finally {
  await browser.close();
}
